// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "example.agent.tool@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const TOOL_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const TOOL_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_tool { () => { "{\"capability_id\":\"example.agent.tool@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"execute\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_tool_client { () => { "{\"capability_id\":\"example.agent.tool@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_tool_client { () => { "{\"capability_id\":\"example.agent.tool@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const EXECUTE_OPERATION: &str = "execute";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteRequest {
    #[serde(rename = "input")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteResponse {
    #[serde(rename = "output")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub output: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExecuteError {
    Denied,
    InvalidInput,
    UnknownTool,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Tool;
impl RequestCapability for Tool {
    type Request = ExecuteRequest;
    type Response = ExecuteResponse;
    type DomainError = ExecuteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXECUTE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ToolRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).execute(context, request)
    }
}

impl serde::Serialize for ExecuteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Denied => serializer.serialize_str("denied"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::UnknownTool => serializer.serialize_str("unknown_tool"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExecuteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "denied" => Ok(Self::Denied),
                "invalid_input" => Ok(Self::InvalidInput),
                "unknown_tool" => Ok(Self::UnknownTool),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_execute_request(value: &ExecuteRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_request(wire: &str) -> Result<ExecuteRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_response(value: &ExecuteResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_response(wire: &str) -> Result<ExecuteResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_error(value: &ExecuteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_error(wire: &str) -> Result<ExecuteError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoToolExecuteResult {
    fn __lenso_into_result(self) -> Result<Result<ExecuteResponse, ExecuteError>, RuntimeFailure>;
}
impl __LensoIntoToolExecuteResult for Result<ExecuteResponse, ExecuteError> {
    fn __lenso_into_result(self) -> Result<Result<ExecuteResponse, ExecuteError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoToolExecuteResult for Result<Result<ExecuteResponse, ExecuteError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ExecuteResponse, ExecuteError>, RuntimeFailure> { self }
}
impl __LensoIntoToolExecuteResult for Result<ExecuteResponse, lenso_plugin_authoring::PluginError<ExecuteError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ExecuteResponse, ExecuteError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoToolExecuteResult for Result<ExecuteResponse, ToolInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ExecuteResponse, ExecuteError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ToolInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ToolInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ToolProvider: fmt::Debug + 'static {
    fn execute(&self, context: InvocationContext, request: ExecuteRequest) -> NativeRequestFuture<Tool>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_tool {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportTool;
        impl $crate::ToolProvider for $plugin {
        fn execute(&self, context: __LensoNativeSupportTool::InvocationContext, request: $crate::ExecuteRequest) -> __LensoNativeSupportTool::NativeRequestFuture<$crate::Tool> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::execute(&plugin, context, request).await;
                $crate::__LensoIntoToolExecuteResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct ToolRequestEndpoint { provider: Rc<dyn ToolProvider> }

#[derive(Debug)]
pub struct ToolEndpoint<P: ToolProvider> { provider: Rc<P>, request_endpoint: ToolRequestEndpoint }
impl<P: ToolProvider> ToolEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ToolProvider> = provider.clone();
        Self { provider, request_endpoint: ToolRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ToolProvider> NativeRequestEndpoint for ToolEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        EXECUTE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            EXECUTE_OPERATION => {
                let Ok(request) = request.downcast::<ExecuteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).execute(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_tool {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ToolEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_tool {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_tool!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ToolClient {
    execute: NativeRequestHandle<Tool>,
}
impl ToolClient {
    pub fn new(handle: NativeRequestHandle<Tool>) -> Self {
        Self { execute: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn execute(&self, request: ExecuteRequest) -> Result<ExecuteResponse, ToolInvocationError> {
        self.execute.invoke(EXECUTE_OPERATION, request).await
            .map_err(ToolInvocationError::Runtime)?
            .map_err(ToolInvocationError::Domain)
    }

    pub async fn execute_with_context(&self, context: InvocationContext, request: ExecuteRequest) -> Result<ExecuteResponse, ToolInvocationError> {
        self.execute.invoke_with_context(EXECUTE_OPERATION, context, request).await
            .map_err(ToolInvocationError::Runtime)?
            .map_err(ToolInvocationError::Domain)
    }
}

impl CapabilityClient for ToolClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            execute: dependencies.one::<Tool>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ToolClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    execute: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Tool>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ToolInvocationError {
    Domain(ExecuteError),
    Runtime(RuntimeFailure),
}
