// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.story.events@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const EVENTS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const EVENTS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_events { () => { "{\"capability_id\":\"lenso.story.events@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"record\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_events_client { () => { "{\"capability_id\":\"lenso.story.events@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_events_client { () => { "{\"capability_id\":\"lenso.story.events@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const RECORD_OPERATION: &str = "record";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RecordRequest {
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_id: String,
    #[serde(rename = "event_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_type: String,
    #[serde(rename = "event_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_version: i64,
    #[serde(rename = "facts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub facts: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "subject_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RecordError {
    ConflictingEventId,
    InvalidEvent,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Events;
impl RequestCapability for Events {
    type Request = RecordRequest;
    type Response = ();
    type DomainError = RecordError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RECORD_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<EventsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).record(context, request)
    }
}

impl serde::Serialize for RecordError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ConflictingEventId => serializer.serialize_str("conflicting_event_id"),
            Self::InvalidEvent => serializer.serialize_str("invalid_event"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RecordError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflicting_event_id" => Ok(Self::ConflictingEventId),
                "invalid_event" => Ok(Self::InvalidEvent),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_record_request(value: &RecordRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_record_request(wire: &str) -> Result<RecordRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_record_response(value: &()) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_record_response(wire: &str) -> Result<(), serde_json::Error> { decode_portable_json(wire) }
pub fn encode_record_error(value: &RecordError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_record_error(wire: &str) -> Result<RecordError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoEventsRecordResult {
    fn __lenso_into_result(self) -> Result<Result<(), RecordError>, RuntimeFailure>;
}
impl __LensoIntoEventsRecordResult for Result<(), RecordError> {
    fn __lenso_into_result(self) -> Result<Result<(), RecordError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoEventsRecordResult for Result<Result<(), RecordError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<(), RecordError>, RuntimeFailure> { self }
}
impl __LensoIntoEventsRecordResult for Result<(), lenso_plugin_authoring::PluginError<RecordError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<(), RecordError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoEventsRecordResult for Result<(), EventsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<(), RecordError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(EventsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(EventsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait EventsProvider: fmt::Debug + 'static {
    fn record(&self, context: InvocationContext, request: RecordRequest) -> NativeRequestFuture<Events>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_events {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportEvents;
        impl $crate::EventsProvider for $plugin {
        fn record(&self, context: __LensoNativeSupportEvents::InvocationContext, request: $crate::RecordRequest) -> __LensoNativeSupportEvents::NativeRequestFuture<$crate::Events> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::record(&plugin, context, request).await;
                $crate::__LensoIntoEventsRecordResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct EventsRequestEndpoint { provider: Rc<dyn EventsProvider> }

#[derive(Debug)]
pub struct EventsEndpoint<P: EventsProvider> { provider: Rc<P>, request_endpoint: EventsRequestEndpoint }
impl<P: EventsProvider> EventsEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn EventsProvider> = provider.clone();
        Self { provider, request_endpoint: EventsRequestEndpoint { provider: request_provider } }
    }
}

impl<P: EventsProvider> NativeRequestEndpoint for EventsEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        RECORD_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            RECORD_OPERATION => {
                let Ok(request) = request.downcast::<RecordRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).record(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_events {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::EventsEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_events {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_events!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct EventsClient {
    record: NativeRequestHandle<Events>,
}
impl EventsClient {
    pub fn new(handle: NativeRequestHandle<Events>) -> Self {
        Self { record: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn record(&self, request: RecordRequest) -> Result<(), EventsInvocationError> {
        self.record.invoke(RECORD_OPERATION, request).await
            .map_err(EventsInvocationError::Runtime)?
            .map_err(EventsInvocationError::Domain)
    }

    pub async fn record_with_context(&self, context: InvocationContext, request: RecordRequest) -> Result<(), EventsInvocationError> {
        self.record.invoke_with_context(RECORD_OPERATION, context, request).await
            .map_err(EventsInvocationError::Runtime)?
            .map_err(EventsInvocationError::Domain)
    }
}

impl CapabilityClient for EventsClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            record: dependencies.one::<Events>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for EventsClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    record: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Events>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum EventsInvocationError {
    Domain(RecordError),
    Runtime(RuntimeFailure),
}
