use std::{net::SocketAddr, time::Duration};

use lenso_capability_secure_greeting::CAPABILITY_ID;
use lenso_vnext_web_ui::{MetadataScenario, ORDERS_PACKAGE_ID, WebUiFixture};
use tokio::{
    io::{AsyncReadExt, AsyncWriteExt},
    net::TcpStream,
    process::Command,
    task::LocalSet,
};

#[test]
fn plugin_root_materializes_explicit_plugins_entrypoints_and_bindings_before_boot() {
    let fixture = WebUiFixture::orders();
    let root = fixture.plugin_root();
    let root_without_web = fixture.clone().without_web().plugin_root();
    assert_ne!(
        serde_json::to_vec_pretty(&root).unwrap(),
        serde_json::to_vec_pretty(&root_without_web).unwrap()
    );
    let plan = fixture
        .resolved_plan()
        .expect("the target-owned Web profile should resolve");

    let instances = plan.plugin_instances();
    let orders_backend = instances
        .iter()
        .find(|instance| instance.instance_key() == "orders/default")
        .expect("business Plugin should be selected");
    let orders_ui = instances
        .iter()
        .find(|instance| instance.instance_key() == "orders-ui/default")
        .expect("UI Contribution Plugin should be selected");

    assert_eq!(orders_backend.package_id(), ORDERS_PACKAGE_ID);
    assert_eq!(orders_backend.entrypoint(), "backend");
    assert_eq!(orders_ui.package_id(), ORDERS_PACKAGE_ID);
    assert_eq!(orders_ui.entrypoint(), "ui");
    assert!(
        instances
            .iter()
            .any(|instance| instance.instance_key() == "web-shell/default")
    );
    assert!(
        instances
            .iter()
            .any(|instance| instance.instance_key() == "browser-adapter/default")
    );
    assert!(plan.capability_bindings().iter().any(|binding| {
        binding.consumer_instance() == "web-shell/default"
            && binding.provider_instance() == "orders-ui/default"
            && binding.capability_id() == "lenso.ui.contribution@1"
    }));
}

#[test]
fn host_catalog_keeps_browser_and_ui_on_the_same_greeting_provider() {
    let plan = WebUiFixture::orders().resolved_plan().unwrap();
    let providers = plan
        .capability_bindings()
        .iter()
        .filter(|binding| {
            binding.capability_id() == CAPABILITY_ID
                && matches!(
                    binding.consumer_instance(),
                    "browser-adapter/default" | "orders-ui/default"
                )
        })
        .map(lenso_app_plan::CapabilityBinding::provider_instance)
        .collect::<Vec<_>>();
    assert_eq!(providers, vec!["orders/default", "orders/default"]);
}

#[tokio::test(flavor = "current_thread")]
async fn route_assets_and_allowlisted_generated_client_run_after_app_readiness() {
    LocalSet::new()
        .run_until(async {
            let running = WebUiFixture::orders()
                .start()
                .await
                .expect("target-owned Web App should start");
            assert!(running.app().is_ready());
            let expected_url = format!("http://{}/orders", running.local_addr().unwrap());
            assert_eq!(
                running.launched_url().as_deref(),
                Some(expected_url.as_str())
            );

            let page = request(running.local_addr().unwrap(), "GET", "/orders", None, None).await;
            assert_eq!(page.status, 200);
            assert!(page.body.contains("<h1>Orders</h1>"));
            assert!(page.body.contains("/assets/orders.js"));

            let asset = request(
                running.local_addr().unwrap(),
                "GET",
                "/assets/orders.js",
                None,
                None,
            )
            .await;
            assert_eq!(asset.status, 200);
            assert!(asset.body.contains("addEventListener"));

            let client = request(
                running.local_addr().unwrap(),
                "GET",
                "/assets/generated/secure-greeting.js",
                None,
                None,
            )
            .await;
            assert_eq!(client.status, 200);
            assert!(client.body.contains("@generated by lenso-contract-codegen"));
            assert!(client.body.contains("createSecureGreetingClient"));

            let allowed = request(
                running.local_addr().unwrap(),
                "POST",
                "/api/capabilities/example.secure-greeting@1/greet",
                Some("good-token"),
                Some(r#"{"name":"Ada"}"#),
            )
            .await;
            assert_eq!(allowed.status, 200);
            assert_eq!(
                allowed.body,
                r#"{"ok":true,"value":{"message":"Hello, Ada (user-123)!"}}"#
            );

            let denied = request(
                running.local_addr().unwrap(),
                "POST",
                "/api/capabilities/example.secure-greeting@1/greet",
                Some("forbidden-token"),
                Some(r#"{"name":"Ada"}"#),
            )
            .await;
            assert_eq!(denied.status, 403);
            assert_eq!(
                denied.body,
                r#"{"ok":false,"error":{"kind":"domain","error":"not_allowed"}}"#
            );

            let ambient = request(
                running.local_addr().unwrap(),
                "POST",
                "/api/invoke",
                Some("good-token"),
                Some(r#"{"capability":"example.secure-greeting@1"}"#),
            )
            .await;
            assert_eq!(ambient.status, 404);

            running.shutdown(Duration::from_secs(1)).await;
        })
        .await;
}

#[ignore = "requires Bun; CI runs this exact generated-client test after installing Bun"]
#[tokio::test(flavor = "current_thread")]
async fn generated_browser_client_invokes_the_allowlisted_app_capability() {
    LocalSet::new()
        .run_until(async {
            let running = WebUiFixture::orders()
                .start()
                .await
                .expect("target-owned Web App should start");
            let browser_result = run_generated_client(running.local_addr().unwrap()).await;
            assert_eq!(
                browser_result,
                r#"{"ok":true,"value":{"message":"Hello, Ada (user-123)!"}}"#
            );
            running.shutdown(Duration::from_secs(1)).await;
        })
        .await;
}

#[tokio::test(flavor = "current_thread")]
async fn generated_client_transport_preserves_unknown_and_protocol_errors() {
    LocalSet::new()
        .run_until(async {
            let running = WebUiFixture::orders().start().await.unwrap();
            let address = running.local_addr().unwrap();
            let unknown = request(
                address,
                "POST",
                "/api/capabilities/example.secure-greeting@1/greet",
                Some("good-token"),
                Some(r#"{"name":"Future"}"#),
            )
            .await;
            assert_eq!(unknown.status, 422);
            assert_eq!(
                unknown.body,
                r#"{"ok":false,"error":{"kind":"domain","error":{"code":"future_rule","payload":{"retry":false},"source":"orders"}}}"#
            );

            let malformed = request(
                address,
                "POST",
                "/api/capabilities/example.secure-greeting@1/greet",
                Some("good-token"),
                Some("{"),
            )
            .await;
            assert_eq!(malformed.status, 400);
            assert!(malformed.body.contains(r#""kind":"runtime""#));
            assert!(malformed.body.contains(r#""kind":"protocol_violation""#));
            running.shutdown(Duration::from_secs(1)).await;
        })
        .await;
}

async fn run_generated_client(address: SocketAddr) -> String {
    let origin = format!("http://{address}");
    let script = r#"
const origin = process.argv[1];
const source = await fetch(`${origin}/assets/generated/secure-greeting.js`).then((response) => response.text());
const { unlink } = await import("node:fs/promises");
const { join } = await import("node:path");
const { pathToFileURL } = await import("node:url");
const modulePath = join(process.cwd(), `lenso-generated-client-${process.pid}.mjs`);
await Bun.write(modulePath, source);
try {
  const { createSecureGreetingClient } = await import(pathToFileURL(modulePath).href);
  let rejectedMalformedEnvelope = false;
  try {
    const malformedTransport = async () => ({ json: async () => ({ ok: true }) });
    await createSecureGreetingClient(malformedTransport).greet({ name: "Ada" }, "good-token");
  } catch {
    rejectedMalformedEnvelope = true;
  }
  if (!rejectedMalformedEnvelope) throw new Error("generated client accepted a malformed result envelope");
  const transport = (path, init) => fetch(`${origin}${path}`, init);
  const result = await createSecureGreetingClient(transport).greet({ name: "Ada" }, "good-token");
  process.stdout.write(JSON.stringify(result));
} finally {
  await unlink(modulePath).catch(() => {});
}
"#;
    let output = Command::new("bun")
        .args(["--eval", script, &origin])
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .output()
        .await
        .expect("Bun should execute the generated browser client");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("Bun output should be UTF-8")
}

#[tokio::test(flavor = "current_thread")]
async fn missing_or_colliding_contribution_metadata_fails_before_readiness() {
    LocalSet::new()
        .run_until(async {
            for (scenario, expected) in [
                (MetadataScenario::MissingRoute, "route must start with `/`"),
                (MetadataScenario::CollidingRoute, "route collision"),
            ] {
                let error = WebUiFixture::orders()
                    .with_metadata_scenario(scenario)
                    .start()
                    .await
                    .expect_err("invalid contribution metadata must fail startup");
                let error = format!("{error:?}");
                assert!(error.contains(expected), "{error}");
            }
        })
        .await;
}

#[tokio::test(flavor = "current_thread")]
async fn removing_web_plugins_leaves_non_ui_business_invocation_unchanged() {
    LocalSet::new()
        .run_until(async {
            let running = WebUiFixture::orders()
                .without_web()
                .start()
                .await
                .expect("the non-Web App should still start");
            assert!(running.app().is_ready());
            assert!(running.local_addr().is_none());
            assert_eq!(
                running
                    .invoke_worker("good-token", "Ada")
                    .await
                    .expect("non-UI worker invocation should succeed"),
                "Hello, Ada (user-123)!"
            );
            running.shutdown(Duration::from_secs(1)).await;
        })
        .await;
}

#[derive(Debug)]
struct Response {
    status: u16,
    body: String,
}

async fn request(
    address: SocketAddr,
    method: &str,
    path: &str,
    token: Option<&str>,
    body: Option<&str>,
) -> Response {
    let mut stream = TcpStream::connect(address)
        .await
        .expect("connect to Browser Adapter");
    let body = body.unwrap_or_default();
    let authorization = token.map_or_else(String::new, |token| {
        format!("Authorization: Bearer {token}\r\n")
    });
    let wire = format!(
        "{method} {path} HTTP/1.1\r\nHost: {address}\r\n{authorization}Content-Length: {}\r\nConnection: close\r\n\r\n{body}",
        body.len()
    );
    stream
        .write_all(wire.as_bytes())
        .await
        .expect("write HTTP request");
    let mut response = Vec::new();
    stream
        .read_to_end(&mut response)
        .await
        .expect("read HTTP response");
    let response = String::from_utf8(response).expect("response should be UTF-8");
    let (head, body) = response
        .split_once("\r\n\r\n")
        .expect("HTTP response framing");
    let status = head
        .split_whitespace()
        .nth(1)
        .expect("HTTP status")
        .parse()
        .expect("numeric HTTP status");
    Response {
        status,
        body: body.to_owned(),
    }
}
