// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "example.agent.model@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const MODEL_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const MODEL_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_model { () => { "{\"capability_id\":\"example.agent.model@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"complete\"],\"operation_kinds\":{\"complete\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_model_client { () => { "{\"capability_id\":\"example.agent.model@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_model_client { () => { "{\"capability_id\":\"example.agent.model@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const COMPLETE_OPERATION: &str = "complete";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteRequest {
    #[serde(rename = "memory")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub memory: Vec<String>,
    #[serde(rename = "prompt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub prompt: String,
    #[serde(rename = "tool_output")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub tool_output: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteResponse {
    #[serde(rename = "delta")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delta: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompleteError {
    ContextTooLarge,
    InvalidPrompt,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Model;
pub type ModelEvent = StreamEvent<CompleteResponse, CompleteError>;
impl StreamCapability for Model {
    type OpenRequest = CompleteRequest;
    type Message = CompleteResponse;
    type DomainError = CompleteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for CompleteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContextTooLarge => serializer.serialize_str("context_too_large"),
            Self::InvalidPrompt => serializer.serialize_str("invalid_prompt"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CompleteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "context_too_large" => Ok(Self::ContextTooLarge),
                "invalid_prompt" => Ok(Self::InvalidPrompt),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_complete_request(value: &CompleteRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_request(wire: &str) -> Result<CompleteRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_response(value: &CompleteResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_response(wire: &str) -> Result<CompleteResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_error(value: &CompleteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_error(wire: &str) -> Result<CompleteError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoModelCompleteStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ModelInvocationError>;
}
impl<S> __LensoIntoModelCompleteStreamResult for Result<S, CompleteError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ModelInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(ModelInvocationError::Domain)
    }
}
impl<S> __LensoIntoModelCompleteStreamResult for Result<S, lenso_plugin_authoring::PluginError<CompleteError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ModelInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(ModelInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(ModelInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoModelCompleteStreamResult for Result<S, ModelInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ModelInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

pub trait ModelProvider: fmt::Debug + 'static {
    fn complete(&self, context: InvocationContext, request: CompleteRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, ModelInvocationError>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_model {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportModel;
        impl $crate::ModelProvider for $plugin {
        fn complete(&self, context: __LensoNativeSupportModel::InvocationContext, request: $crate::CompleteRequest) -> __LensoNativeSupportModel::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportModel::NativeStreamSession>, $crate::ModelInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::complete(&plugin, context, request).await;
                $crate::__LensoIntoModelCompleteStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
pub struct ModelEndpoint<P: ModelProvider> { provider: Rc<P> }
impl<P: ModelProvider> ModelEndpoint<P> {
    pub fn new(provider: P) -> Self { Self { provider: Rc::new(provider) } }
}

impl<P: ModelProvider> NativeStreamEndpoint for ModelEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        COMPLETE_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            COMPLETE_OPERATION => {
                let Ok(request) = request.downcast::<CompleteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.complete(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(ModelInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ModelInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_model {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ModelEndpoint::new($provider));
        (
            vec![],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_model {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_model!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ModelClient {
    complete: NativeStreamHandle<Model>,
}
impl ModelClient {
    pub fn new(handle: NativeStreamHandle<Model>) -> Self {
        Self { complete: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn complete(&self, request: CompleteRequest) -> Result<NativeStream<Model>, ModelInvocationError> {
        self.complete.open(COMPLETE_OPERATION, request).await
            .map_err(ModelInvocationError::Runtime)?
            .map_err(ModelInvocationError::Domain)
    }

    pub async fn complete_with_context(&self, context: InvocationContext, request: CompleteRequest) -> Result<NativeStream<Model>, ModelInvocationError> {
        self.complete.open_with_context(COMPLETE_OPERATION, context, request).await
            .map_err(ModelInvocationError::Runtime)?
            .map_err(ModelInvocationError::Domain)
    }
}

impl CapabilityClient for ModelClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            complete: dependencies.one_stream::<Model>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ModelClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    complete: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Model>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ModelInvocationError {
    Domain(CompleteError),
    Runtime(RuntimeFailure),
}
