/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.jobs@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:34fca9ad91952dd4eb9da844b94925cd0a54928843c803ed51e1c6ccb11d690d";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object, Runtime extends DependencyInvoker = DependencyInvoker> extends CapabilityDependencyBinding<Client, Runtime> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one", Runtime>;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional", Runtime>;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many", Runtime>;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface ClaimRequest {
  queue: string;
}

export interface ClaimResponse {
  attempt: number;
  job_id: string;
  kind: string;
  lease_expires_at: Timestamp;
  lease_token: string;
  max_attempts: number;
  payload: Record<string, unknown>;
  queue: string;
}

export interface CompleteRequest {
  job_id: string;
  lease_token: string;
}

export interface CompleteResponse {
  completed: boolean;
}

export interface EnqueueRequest {
  available_at: Timestamp;
  idempotency_key: string;
  kind: string;
  max_attempts: number;
  payload: Record<string, unknown>;
  queue: string;
}

export interface EnqueueResponse {
  created: boolean;
  job_id: string;
}

export interface FailRequest {
  failure_code: string;
  job_id: string;
  lease_token: string;
  retryable: boolean;
}

export interface FailResponse {
  available_at: Timestamp | null;
  status: "queued" | "failed";
}

export interface InspectRequest {
  job_id: string;
}

export interface InspectResponse {
  attempts: number;
  available_at: Timestamp;
  created_at: Timestamp;
  job_id: string;
  kind: string;
  last_failure_code?: string | null;
  lease_expires_at?: Timestamp | null;
  max_attempts: number;
  queue: string;
  status: "queued" | "running" | "succeeded" | "failed";
  updated_at: Timestamp;
}

export interface RenewRequest {
  job_id: string;
  lease_token: string;
}

export interface RenewResponse {
  lease_expires_at: Timestamp;
}

export type ClaimError = "invalid_queue" | "no_job_available" | "unauthorized" | UnknownDomainError;
export type ClaimInvocationError = { readonly kind: "domain"; readonly error: ClaimError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ClaimResult = { readonly ok: true; readonly value: ClaimResponse } | { readonly ok: false; readonly error: ClaimInvocationError };
export type CompleteError = "invalid_lease" | "unauthorized" | UnknownDomainError;
export type CompleteInvocationError = { readonly kind: "domain"; readonly error: CompleteError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type CompleteResult = { readonly ok: true; readonly value: CompleteResponse } | { readonly ok: false; readonly error: CompleteInvocationError };
export type EnqueueError = "idempotency_conflict" | "invalid_job" | "unauthorized" | UnknownDomainError;
export type EnqueueInvocationError = { readonly kind: "domain"; readonly error: EnqueueError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type EnqueueResult = { readonly ok: true; readonly value: EnqueueResponse } | { readonly ok: false; readonly error: EnqueueInvocationError };
export type FailError = "invalid_failure" | "invalid_lease" | "unauthorized" | UnknownDomainError;
export type FailInvocationError = { readonly kind: "domain"; readonly error: FailError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type FailResult = { readonly ok: true; readonly value: FailResponse } | { readonly ok: false; readonly error: FailInvocationError };
export type InspectError = "job_not_found" | "unauthorized" | UnknownDomainError;
export type InspectInvocationError = { readonly kind: "domain"; readonly error: InspectError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type InspectResult = { readonly ok: true; readonly value: InspectResponse } | { readonly ok: false; readonly error: InspectInvocationError };
export type RenewError = "invalid_lease" | "unauthorized" | UnknownDomainError;
export type RenewInvocationError = { readonly kind: "domain"; readonly error: RenewError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type RenewResult = { readonly ok: true; readonly value: RenewResponse } | { readonly ok: false; readonly error: RenewInvocationError };
export function encodeClaimRequest(value: ClaimRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeClaimRequest(wire: string): ClaimRequest { return lensoContractRuntime.decodePortableJson<ClaimRequest>(wire); }
export function encodeClaimResponse(value: ClaimResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeClaimResponse(wire: string): ClaimResponse { return lensoContractRuntime.decodePortableJson<ClaimResponse>(wire); }
export function encodeClaimError(value: ClaimError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeClaimError(wire: string): ClaimError { return lensoContractRuntime.decodeDomainError<ClaimError>(wire, ["invalid_queue", "no_job_available", "unauthorized"]); }

export function encodeCompleteRequest(value: CompleteRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeCompleteRequest(wire: string): CompleteRequest { return lensoContractRuntime.decodePortableJson<CompleteRequest>(wire); }
export function encodeCompleteResponse(value: CompleteResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeCompleteResponse(wire: string): CompleteResponse { return lensoContractRuntime.decodePortableJson<CompleteResponse>(wire); }
export function encodeCompleteError(value: CompleteError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeCompleteError(wire: string): CompleteError { return lensoContractRuntime.decodeDomainError<CompleteError>(wire, ["invalid_lease", "unauthorized"]); }

export function encodeEnqueueRequest(value: EnqueueRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeEnqueueRequest(wire: string): EnqueueRequest { return lensoContractRuntime.decodePortableJson<EnqueueRequest>(wire); }
export function encodeEnqueueResponse(value: EnqueueResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeEnqueueResponse(wire: string): EnqueueResponse { return lensoContractRuntime.decodePortableJson<EnqueueResponse>(wire); }
export function encodeEnqueueError(value: EnqueueError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeEnqueueError(wire: string): EnqueueError { return lensoContractRuntime.decodeDomainError<EnqueueError>(wire, ["idempotency_conflict", "invalid_job", "unauthorized"]); }

export function encodeFailRequest(value: FailRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeFailRequest(wire: string): FailRequest { return lensoContractRuntime.decodePortableJson<FailRequest>(wire); }
export function encodeFailResponse(value: FailResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeFailResponse(wire: string): FailResponse { return lensoContractRuntime.decodePortableJson<FailResponse>(wire); }
export function encodeFailError(value: FailError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeFailError(wire: string): FailError { return lensoContractRuntime.decodeDomainError<FailError>(wire, ["invalid_failure", "invalid_lease", "unauthorized"]); }

export function encodeInspectRequest(value: InspectRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeInspectRequest(wire: string): InspectRequest { return lensoContractRuntime.decodePortableJson<InspectRequest>(wire); }
export function encodeInspectResponse(value: InspectResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeInspectResponse(wire: string): InspectResponse { return lensoContractRuntime.decodePortableJson<InspectResponse>(wire); }
export function encodeInspectError(value: InspectError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeInspectError(wire: string): InspectError { return lensoContractRuntime.decodeDomainError<InspectError>(wire, ["job_not_found", "unauthorized"]); }

export function encodeRenewRequest(value: RenewRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeRenewRequest(wire: string): RenewRequest { return lensoContractRuntime.decodePortableJson<RenewRequest>(wire); }
export function encodeRenewResponse(value: RenewResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeRenewResponse(wire: string): RenewResponse { return lensoContractRuntime.decodePortableJson<RenewResponse>(wire); }
export function encodeRenewError(value: RenewError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeRenewError(wire: string): RenewError { return lensoContractRuntime.decodeDomainError<RenewError>(wire, ["invalid_lease", "unauthorized"]); }


export interface JobsClient {
  claim(request: ClaimRequest, context?: InvocationContext): Promise<ClaimResult>;
  complete(request: CompleteRequest, context?: InvocationContext): Promise<CompleteResult>;
  enqueue(request: EnqueueRequest, context?: InvocationContext): Promise<EnqueueResult>;
  fail(request: FailRequest, context?: InvocationContext): Promise<FailResult>;
  inspect(request: InspectRequest, context?: InvocationContext): Promise<InspectResult>;
  renew(request: RenewRequest, context?: InvocationContext): Promise<RenewResult>;
}

export interface JobsProvider {
  claim(context: InvocationContext, request: ClaimRequest): Promise<ClaimResult>;
  complete(context: InvocationContext, request: CompleteRequest): Promise<CompleteResult>;
  enqueue(context: InvocationContext, request: EnqueueRequest): Promise<EnqueueResult>;
  fail(context: InvocationContext, request: FailRequest): Promise<FailResult>;
  inspect(context: InvocationContext, request: InspectRequest): Promise<InspectResult>;
  renew(context: InvocationContext, request: RenewRequest): Promise<RenewResult>;
}

export const Jobs: CapabilityContractReference<JobsClient, JobsProvider, InteractionDependencyInvoker> = { kind: "lenso.capability", ...bindJobsDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "JobsClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["claim", "complete", "enqueue", "fail", "inspect", "renew"], stream_operations: [], event_operations: [] }, bindProvider: bindJobsProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const JOBS_CONTRACT = Jobs;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindJobsProvider(
  provider: JobsProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["claim", "complete", "enqueue", "fail", "inspect", "renew"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "claim": {
        let request: ClaimRequest;
        try {
          request = decodeClaimRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.claim(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeClaimResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeClaimError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "complete": {
        let request: CompleteRequest;
        try {
          request = decodeCompleteRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.complete(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeCompleteResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeCompleteError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "enqueue": {
        let request: EnqueueRequest;
        try {
          request = decodeEnqueueRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.enqueue(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeEnqueueResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeEnqueueError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "fail": {
        let request: FailRequest;
        try {
          request = decodeFailRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.fail(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeFailResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeFailError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "inspect": {
        let request: InspectRequest;
        try {
          request = decodeInspectRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.inspect(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeInspectResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeInspectError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "renew": {
        let request: RenewRequest;
        try {
          request = decodeRenewRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.renew(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeRenewResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeRenewError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = JobsProvider;
export const bindProvider = bindJobsProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export type InteractionDependencyInvoker = DependencyInvoker & {
  readonly providerInstance: string;
  openStream(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderStreamOpenOutcome>;
  publishEvent(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderEventPublishOutcome>;
};

export interface CapabilityDependencyBinding<Client, Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: Runtime): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many", Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client, Runtime>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function dependencyRuntimeError(failure: RuntimeFailure): Error {
  return Object.assign(new Error(`Capability dependency failed: ${failure.kind}`), { failure });
}

function dependencyFailure(error: unknown): RuntimeFailure {
  if (typeof error === "object" && error !== null && "failure" in error) return (error as { failure: RuntimeFailure }).failure;
  return { kind: "plugin_failure", detail: dependencyErrorMessage(error) };
}

export function bindJobsDependency(): CapabilityDependencyBinding<JobsClient, InteractionDependencyInvoker> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["claim", "complete", "enqueue", "fail", "inspect", "renew"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async claim(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeClaimRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("claim", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeClaimResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeClaimError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async complete(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeCompleteRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("complete", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeCompleteResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeCompleteError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async enqueue(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeEnqueueRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("enqueue", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeEnqueueResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeEnqueueError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async fail(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeFailRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("fail", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeFailResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeFailError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async inspect(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeInspectRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("inspect", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeInspectResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeInspectError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async renew(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeRenewRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("renew", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeRenewResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeRenewError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindJobsDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
