// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "example.document-store@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:a68214adfc45c089e808b4b2a0d7ad0d8a6894433ac53af63e95a5abaff10914";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const DOCUMENT_STORE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const DOCUMENT_STORE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const DOCUMENT_STORE_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const DOCUMENT_STORE_CONTRACT: CapabilityReference<DocumentStoreClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_document_store { () => { "{\"capability_id\":\"example.document-store@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"put\",\"read\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_document_store_client {
    () => { "{\"capability_id\":\"example.document-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.document-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_document_store_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.document-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_document_store_client {
    () => { "{\"capability_id\":\"example.document-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.document-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const PUT_OPERATION: &str = "put";
pub const READ_OPERATION: &str = "read";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PutRequest {
    #[serde(rename = "document")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub document: String,
    #[serde(rename = "text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PutResponse {
    #[serde(rename = "stored")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub stored: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PutError {
    NotFound,
    Rejected,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRequest {
    #[serde(rename = "document")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub document: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponse {
    #[serde(rename = "text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadError {
    NotFound,
    Rejected,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct DocumentStorePut;
impl RequestCapability for DocumentStorePut {
    type Request = PutRequest;
    type Response = PutResponse;
    type DomainError = PutError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PUT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DocumentStoreRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).put(context, request)
    }
}

#[derive(Debug)]
pub struct DocumentStoreRead;
impl RequestCapability for DocumentStoreRead {
    type Request = ReadRequest;
    type Response = ReadResponse;
    type DomainError = ReadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DocumentStoreRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read(context, request)
    }
}

impl serde::Serialize for PutError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Rejected => serializer.serialize_str("rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PutError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "not_found" => Ok(Self::NotFound),
                "rejected" => Ok(Self::Rejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Rejected => serializer.serialize_str("rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "not_found" => Ok(Self::NotFound),
                "rejected" => Ok(Self::Rejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_put_request(value: &PutRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_request(wire: &str) -> Result<PutRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_put_response(value: &PutResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_response(wire: &str) -> Result<PutResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_put_error(value: &PutError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_error(wire: &str) -> Result<PutError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_request(value: &ReadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_request(wire: &str) -> Result<ReadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_response(value: &ReadResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_response(wire: &str) -> Result<ReadResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_error(value: &ReadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_error(wire: &str) -> Result<ReadError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoDocumentStorePutResult {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure>;
}
impl __LensoIntoDocumentStorePutResult for Result<PutResponse, PutError> {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDocumentStorePutResult for Result<Result<PutResponse, PutError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure> { self }
}
impl __LensoIntoDocumentStorePutResult for Result<PutResponse, lenso_plugin_authoring::PluginError<PutError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDocumentStorePutResult for Result<PutResponse, DocumentStorePutInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<PutResponse, PutError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DocumentStorePutInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DocumentStorePutInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoDocumentStoreReadResult {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure>;
}
impl __LensoIntoDocumentStoreReadResult for Result<ReadResponse, ReadError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDocumentStoreReadResult for Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { self }
}
impl __LensoIntoDocumentStoreReadResult for Result<ReadResponse, lenso_plugin_authoring::PluginError<ReadError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDocumentStoreReadResult for Result<ReadResponse, DocumentStoreReadInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DocumentStoreReadInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DocumentStoreReadInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait DocumentStoreProvider: fmt::Debug + 'static {
    fn put(&self, context: InvocationContext, request: PutRequest) -> NativeRequestFuture<DocumentStorePut>;
    fn read(&self, context: InvocationContext, request: ReadRequest) -> NativeRequestFuture<DocumentStoreRead>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_document_store {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDocumentStore;
        impl $crate::DocumentStoreProvider for $plugin {
        fn put(&self, context: __LensoNativeSupportDocumentStore::InvocationContext, request: $crate::PutRequest) -> __LensoNativeSupportDocumentStore::NativeRequestFuture<$crate::DocumentStorePut> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::put(&plugin, context, request).await;
                $crate::__LensoIntoDocumentStorePutResult::__lenso_into_result(result)
            })
        }
        fn read(&self, context: __LensoNativeSupportDocumentStore::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportDocumentStore::NativeRequestFuture<$crate::DocumentStoreRead> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read(&plugin, context, request).await;
                $crate::__LensoIntoDocumentStoreReadResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_document_store {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDocumentStore;
        impl $crate::DocumentStoreProvider for $object {
        fn put(&self, context: __LensoNativeSupportDocumentStore::InvocationContext, request: $crate::PutRequest) -> __LensoNativeSupportDocumentStore::NativeRequestFuture<$crate::DocumentStorePut> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::put(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoDocumentStorePutResult::__lenso_into_result(result)
            })
        }
        fn read(&self, context: __LensoNativeSupportDocumentStore::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportDocumentStore::NativeRequestFuture<$crate::DocumentStoreRead> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoDocumentStoreReadResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_document_store {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDocumentStore;
        impl $crate::DocumentStoreProvider for $object {
        fn put(&self, context: __LensoNativeSupportDocumentStore::InvocationContext, request: $crate::PutRequest) -> __LensoNativeSupportDocumentStore::NativeRequestFuture<$crate::DocumentStorePut> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::DocumentStoreProvider>::put(plugin.as_ref(), context, request).await
            })
        }
        fn read(&self, context: __LensoNativeSupportDocumentStore::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportDocumentStore::NativeRequestFuture<$crate::DocumentStoreRead> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::DocumentStoreProvider>::read(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct DocumentStoreRequestEndpoint { provider: Rc<dyn DocumentStoreProvider> }

#[derive(Debug)]
pub struct DocumentStoreEndpoint<P: DocumentStoreProvider> { provider: Rc<P>, request_endpoint: DocumentStoreRequestEndpoint }
impl<P: DocumentStoreProvider> DocumentStoreEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn DocumentStoreProvider> = provider.clone();
        Self { provider, request_endpoint: DocumentStoreRequestEndpoint { provider: request_provider } }
    }
}

impl<P: DocumentStoreProvider> NativeRequestEndpoint for DocumentStoreEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        PUT_OPERATION,
        READ_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            PUT_OPERATION => {
                let Ok(request) = request.downcast::<PutRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).put(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_OPERATION => {
                let Ok(request) = request.downcast::<ReadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_document_store {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::DocumentStoreEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_document_store {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_document_store!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct DocumentStoreClient {
    put: NativeRequestHandle<DocumentStorePut>,
    read: NativeRequestHandle<DocumentStoreRead>,
}
impl DocumentStoreClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn put(&self, request: PutRequest) -> Result<PutResponse, DocumentStorePutInvocationError> {
        self.put.invoke(PUT_OPERATION, request).await
            .map_err(DocumentStorePutInvocationError::Runtime)?
            .map_err(DocumentStorePutInvocationError::Domain)
    }

    pub async fn put_with_context(&self, context: InvocationContext, request: PutRequest) -> Result<PutResponse, DocumentStorePutInvocationError> {
        self.put.invoke_with_context(PUT_OPERATION, context, request).await
            .map_err(DocumentStorePutInvocationError::Runtime)?
            .map_err(DocumentStorePutInvocationError::Domain)
    }

    pub async fn read(&self, request: ReadRequest) -> Result<ReadResponse, DocumentStoreReadInvocationError> {
        self.read.invoke(READ_OPERATION, request).await
            .map_err(DocumentStoreReadInvocationError::Runtime)?
            .map_err(DocumentStoreReadInvocationError::Domain)
    }

    pub async fn read_with_context(&self, context: InvocationContext, request: ReadRequest) -> Result<ReadResponse, DocumentStoreReadInvocationError> {
        self.read.invoke_with_context(READ_OPERATION, context, request).await
            .map_err(DocumentStoreReadInvocationError::Runtime)?
            .map_err(DocumentStoreReadInvocationError::Domain)
    }
}

impl CapabilityClient for DocumentStoreClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            put: dependencies.one::<DocumentStorePut>()?,
            read: dependencies.one::<DocumentStoreRead>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for DocumentStoreClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    put: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DocumentStorePut>()?,
                    read: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DocumentStoreRead>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum DocumentStorePutInvocationError {
    Domain(PutError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum DocumentStoreReadInvocationError {
    Domain(ReadError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct DocumentStoreGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> DocumentStoreGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[PUT_OPERATION, READ_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn put(&self, request: &PutRequest) -> Result<PutResponse, lenso_guest_sdk::GuestError<PutError>> {
        self.capability.request(PUT_OPERATION, request)
    }

    pub fn read(&self, request: &ReadRequest) -> Result<ReadResponse, lenso_guest_sdk::GuestError<ReadError>> {
        self.capability.request(READ_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct DocumentStoreJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for DocumentStoreJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[PUT_OPERATION, READ_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            PUT_OPERATION => {
                let value = request.downcast_ref::<PutRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            READ_OPERATION => {
                let value = request.downcast_ref::<ReadRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            PUT_OPERATION => serde_json::from_value::<PutResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            READ_OPERATION => serde_json::from_value::<ReadResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            PUT_OPERATION => serde_json::from_value::<PutError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            READ_OPERATION => serde_json::from_value::<ReadError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            PUT_OPERATION => {
                let request = serde_json::from_value::<PutRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<DocumentStorePut>()?;
                    match handle.invoke_with_context(PUT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            READ_OPERATION => {
                let request = serde_json::from_value::<ReadRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<DocumentStoreRead>()?;
                    match handle.invoke_with_context(READ_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
