// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "example.ops-state@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.1";
pub const DESCRIPTOR_DIGEST: &str = "sha256:ab3104d61861b83495bc17dcef8772e3b130dc0defcc9676933c3258e521f756";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const OPS_STATE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const OPS_STATE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const OPS_STATE_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const OPS_STATE_CONTRACT: CapabilityReference<OpsStateClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_ops_state { () => { "{\"capability_id\":\"example.ops-state@1\",\"descriptor_version\":\"1.1.1\",\"operations\":[\"read\",\"receipt\",\"update\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":16,\"max_concurrency\":2},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_ops_state_client {
    () => { "{\"capability_id\":\"example.ops-state@1\",\"descriptor_version\":\"1.1.1\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.ops-state@1\",\"descriptor_version\":\"1.1.1\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_ops_state_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.ops-state@1\",\"descriptor_version\":\"1.1.1\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_ops_state_client {
    () => { "{\"capability_id\":\"example.ops-state@1\",\"descriptor_version\":\"1.1.1\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.ops-state@1\",\"descriptor_version\":\"1.1.1\",\"cardinality\":\"many\"}") };
}

pub const READ_OPERATION: &str = "read";
pub const RECEIPT_OPERATION: &str = "receipt";
pub const UPDATE_OPERATION: &str = "update";

pub use lenso_contract_runtime::{OptionalValue, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Copy, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponse {
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadError {
    IdempotencyConflict,
    InvalidInput,
    StaleRevision,
    Unavailable,
    UnknownCommit,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReceiptRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReceiptResponse {
    #[serde(rename = "found")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub found: bool,
    #[serde(rename = "label")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub label: OptionalValue<String>,
    #[serde(rename = "receipt_id")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub receipt_id: OptionalValue<String>,
    #[serde(rename = "revision")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub revision: OptionalValue<i64>,
    #[serde(rename = "value")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub value: OptionalValue<i64>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReceiptError {
    IdempotencyConflict,
    InvalidInput,
    StaleRevision,
    Unavailable,
    UnknownCommit,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpdateRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: i64,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpdateResponse {
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
    #[serde(rename = "receipt_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receipt_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UpdateError {
    IdempotencyConflict,
    InvalidInput,
    StaleRevision,
    Unavailable,
    UnknownCommit,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OpsStateRead;
impl RequestCapability for OpsStateRead {
    type Request = ReadRequest;
    type Response = ReadResponse;
    type DomainError = ReadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OpsStateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read(context, request)
    }
}

#[derive(Debug)]
pub struct OpsStateReceipt;
impl RequestCapability for OpsStateReceipt {
    type Request = ReceiptRequest;
    type Response = ReceiptResponse;
    type DomainError = ReceiptError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RECEIPT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OpsStateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).receipt(context, request)
    }
}

#[derive(Debug)]
pub struct OpsStateUpdate;
impl RequestCapability for OpsStateUpdate {
    type Request = UpdateRequest;
    type Response = UpdateResponse;
    type DomainError = UpdateError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != UPDATE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OpsStateRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).update(context, request)
    }
}

impl serde::Serialize for ReadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::StaleRevision => serializer.serialize_str("stale_revision"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::UnknownCommit => serializer.serialize_str("unknown_commit"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_input" => Ok(Self::InvalidInput),
                "stale_revision" => Ok(Self::StaleRevision),
                "unavailable" => Ok(Self::Unavailable),
                "unknown_commit" => Ok(Self::UnknownCommit),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReceiptError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::StaleRevision => serializer.serialize_str("stale_revision"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::UnknownCommit => serializer.serialize_str("unknown_commit"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReceiptError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_input" => Ok(Self::InvalidInput),
                "stale_revision" => Ok(Self::StaleRevision),
                "unavailable" => Ok(Self::Unavailable),
                "unknown_commit" => Ok(Self::UnknownCommit),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for UpdateError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::StaleRevision => serializer.serialize_str("stale_revision"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::UnknownCommit => serializer.serialize_str("unknown_commit"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for UpdateError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_input" => Ok(Self::InvalidInput),
                "stale_revision" => Ok(Self::StaleRevision),
                "unavailable" => Ok(Self::Unavailable),
                "unknown_commit" => Ok(Self::UnknownCommit),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_request(value: &ReadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_request(wire: &str) -> Result<ReadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_response(value: &ReadResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_response(wire: &str) -> Result<ReadResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_error(value: &ReadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_error(wire: &str) -> Result<ReadError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_receipt_request(value: &ReceiptRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_receipt_request(wire: &str) -> Result<ReceiptRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_receipt_response(value: &ReceiptResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_receipt_response(wire: &str) -> Result<ReceiptResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_receipt_error(value: &ReceiptError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_receipt_error(wire: &str) -> Result<ReceiptError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_update_request(value: &UpdateRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_request(wire: &str) -> Result<UpdateRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_update_response(value: &UpdateResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_response(wire: &str) -> Result<UpdateResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_update_error(value: &UpdateError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_error(wire: &str) -> Result<UpdateError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOpsStateReadResult {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure>;
}
impl __LensoIntoOpsStateReadResult for Result<ReadResponse, ReadError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOpsStateReadResult for Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { self }
}
impl __LensoIntoOpsStateReadResult for Result<ReadResponse, lenso_plugin_authoring::PluginError<ReadError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOpsStateReadResult for Result<ReadResponse, OpsStateReadInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OpsStateReadInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OpsStateReadInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOpsStateReceiptResult {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure>;
}
impl __LensoIntoOpsStateReceiptResult for Result<ReceiptResponse, ReceiptError> {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOpsStateReceiptResult for Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> { self }
}
impl __LensoIntoOpsStateReceiptResult for Result<ReceiptResponse, lenso_plugin_authoring::PluginError<ReceiptError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOpsStateReceiptResult for Result<ReceiptResponse, OpsStateReceiptInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReceiptResponse, ReceiptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OpsStateReceiptInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OpsStateReceiptInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOpsStateUpdateResult {
    fn __lenso_into_result(self) -> Result<Result<UpdateResponse, UpdateError>, RuntimeFailure>;
}
impl __LensoIntoOpsStateUpdateResult for Result<UpdateResponse, UpdateError> {
    fn __lenso_into_result(self) -> Result<Result<UpdateResponse, UpdateError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOpsStateUpdateResult for Result<Result<UpdateResponse, UpdateError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<UpdateResponse, UpdateError>, RuntimeFailure> { self }
}
impl __LensoIntoOpsStateUpdateResult for Result<UpdateResponse, lenso_plugin_authoring::PluginError<UpdateError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<UpdateResponse, UpdateError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOpsStateUpdateResult for Result<UpdateResponse, OpsStateUpdateInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<UpdateResponse, UpdateError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OpsStateUpdateInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OpsStateUpdateInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OpsStateProvider: fmt::Debug + 'static {
    fn read(&self, context: InvocationContext, request: ReadRequest) -> NativeRequestFuture<OpsStateRead>;
    fn receipt(&self, context: InvocationContext, request: ReceiptRequest) -> NativeRequestFuture<OpsStateReceipt>;
    fn update(&self, context: InvocationContext, request: UpdateRequest) -> NativeRequestFuture<OpsStateUpdate>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_ops_state {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOpsState;
        impl $crate::OpsStateProvider for $plugin {
        fn read(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateRead> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read(&plugin, context, request).await;
                $crate::__LensoIntoOpsStateReadResult::__lenso_into_result(result)
            })
        }
        fn receipt(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::ReceiptRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateReceipt> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::receipt(&plugin, context, request).await;
                $crate::__LensoIntoOpsStateReceiptResult::__lenso_into_result(result)
            })
        }
        fn update(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::UpdateRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateUpdate> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::update(&plugin, context, request).await;
                $crate::__LensoIntoOpsStateUpdateResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_ops_state {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOpsState;
        impl $crate::OpsStateProvider for $object {
        fn read(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateRead> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOpsStateReadResult::__lenso_into_result(result)
            })
        }
        fn receipt(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::ReceiptRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateReceipt> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::receipt(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOpsStateReceiptResult::__lenso_into_result(result)
            })
        }
        fn update(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::UpdateRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateUpdate> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::update(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoOpsStateUpdateResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_ops_state {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOpsState;
        impl $crate::OpsStateProvider for $object {
        fn read(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateRead> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OpsStateProvider>::read(plugin.as_ref(), context, request).await
            })
        }
        fn receipt(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::ReceiptRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateReceipt> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OpsStateProvider>::receipt(plugin.as_ref(), context, request).await
            })
        }
        fn update(&self, context: __LensoNativeSupportOpsState::InvocationContext, request: $crate::UpdateRequest) -> __LensoNativeSupportOpsState::NativeRequestFuture<$crate::OpsStateUpdate> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::OpsStateProvider>::update(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct OpsStateRequestEndpoint { provider: Rc<dyn OpsStateProvider> }

#[derive(Debug)]
pub struct OpsStateEndpoint<P: OpsStateProvider> { provider: Rc<P>, request_endpoint: OpsStateRequestEndpoint }
impl<P: OpsStateProvider> OpsStateEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OpsStateProvider> = provider.clone();
        Self { provider, request_endpoint: OpsStateRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OpsStateProvider> NativeRequestEndpoint for OpsStateEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_OPERATION,
        RECEIPT_OPERATION,
        UPDATE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_OPERATION => {
                let Ok(request) = request.downcast::<ReadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RECEIPT_OPERATION => {
                let Ok(request) = request.downcast::<ReceiptRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).receipt(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            UPDATE_OPERATION => {
                let Ok(request) = request.downcast::<UpdateRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).update(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_ops_state {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OpsStateEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_ops_state {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_ops_state!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct OpsStateClient {
    read: NativeRequestHandle<OpsStateRead>,
    receipt: NativeRequestHandle<OpsStateReceipt>,
    update: NativeRequestHandle<OpsStateUpdate>,
}
impl OpsStateClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn read(&self, request: ReadRequest) -> Result<ReadResponse, OpsStateReadInvocationError> {
        self.read.invoke(READ_OPERATION, request).await
            .map_err(OpsStateReadInvocationError::Runtime)?
            .map_err(OpsStateReadInvocationError::Domain)
    }

    pub async fn read_with_context(&self, context: InvocationContext, request: ReadRequest) -> Result<ReadResponse, OpsStateReadInvocationError> {
        self.read.invoke_with_context(READ_OPERATION, context, request).await
            .map_err(OpsStateReadInvocationError::Runtime)?
            .map_err(OpsStateReadInvocationError::Domain)
    }

    pub async fn receipt(&self, request: ReceiptRequest) -> Result<ReceiptResponse, OpsStateReceiptInvocationError> {
        self.receipt.invoke(RECEIPT_OPERATION, request).await
            .map_err(OpsStateReceiptInvocationError::Runtime)?
            .map_err(OpsStateReceiptInvocationError::Domain)
    }

    pub async fn receipt_with_context(&self, context: InvocationContext, request: ReceiptRequest) -> Result<ReceiptResponse, OpsStateReceiptInvocationError> {
        self.receipt.invoke_with_context(RECEIPT_OPERATION, context, request).await
            .map_err(OpsStateReceiptInvocationError::Runtime)?
            .map_err(OpsStateReceiptInvocationError::Domain)
    }

    pub async fn update(&self, request: UpdateRequest) -> Result<UpdateResponse, OpsStateUpdateInvocationError> {
        self.update.invoke(UPDATE_OPERATION, request).await
            .map_err(OpsStateUpdateInvocationError::Runtime)?
            .map_err(OpsStateUpdateInvocationError::Domain)
    }

    pub async fn update_with_context(&self, context: InvocationContext, request: UpdateRequest) -> Result<UpdateResponse, OpsStateUpdateInvocationError> {
        self.update.invoke_with_context(UPDATE_OPERATION, context, request).await
            .map_err(OpsStateUpdateInvocationError::Runtime)?
            .map_err(OpsStateUpdateInvocationError::Domain)
    }
}

impl CapabilityClient for OpsStateClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read: dependencies.one::<OpsStateRead>()?,
            receipt: dependencies.one::<OpsStateReceipt>()?,
            update: dependencies.one::<OpsStateUpdate>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OpsStateClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    read: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OpsStateRead>()?,
                    receipt: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OpsStateReceipt>()?,
                    update: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OpsStateUpdate>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OpsStateReadInvocationError {
    Domain(ReadError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OpsStateReceiptInvocationError {
    Domain(ReceiptError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OpsStateUpdateInvocationError {
    Domain(UpdateError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct OpsStateGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> OpsStateGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[READ_OPERATION, RECEIPT_OPERATION, UPDATE_OPERATION], &[], &[])
            .map(|capability| Self { capability })
    }

    pub fn read(&self, request: &ReadRequest) -> Result<ReadResponse, lenso_guest_sdk::GuestError<ReadError>> {
        self.capability.request(READ_OPERATION, request)
    }

    pub fn receipt(&self, request: &ReceiptRequest) -> Result<ReceiptResponse, lenso_guest_sdk::GuestError<ReceiptError>> {
        self.capability.request(RECEIPT_OPERATION, request)
    }

    pub fn update(&self, request: &UpdateRequest) -> Result<UpdateResponse, lenso_guest_sdk::GuestError<UpdateError>> {
        self.capability.request(UPDATE_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct OpsStateJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for OpsStateJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[READ_OPERATION, RECEIPT_OPERATION, UPDATE_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }
    fn event_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            READ_OPERATION => {
                let value = request.downcast_ref::<ReadRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            RECEIPT_OPERATION => {
                let value = request.downcast_ref::<ReceiptRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            UPDATE_OPERATION => {
                let value = request.downcast_ref::<UpdateRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            READ_OPERATION => serde_json::from_value::<ReadResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            RECEIPT_OPERATION => serde_json::from_value::<ReceiptResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            UPDATE_OPERATION => serde_json::from_value::<UpdateResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            READ_OPERATION => serde_json::from_value::<ReadError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            RECEIPT_OPERATION => serde_json::from_value::<ReceiptError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            UPDATE_OPERATION => serde_json::from_value::<UpdateError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_event(&self, operation: &str, _event: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            READ_OPERATION => {
                let request = serde_json::from_value::<ReadRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<OpsStateRead>()?;
                    match handle.invoke_with_context(READ_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            RECEIPT_OPERATION => {
                let request = serde_json::from_value::<ReceiptRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<OpsStateReceipt>()?;
                    match handle.invoke_with_context(RECEIPT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            UPDATE_OPERATION => {
                let request = serde_json::from_value::<UpdateRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<OpsStateUpdate>()?;
                    match handle.invoke_with_context(UPDATE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }

    fn publish_host_event(&self, _dependency: lenso_kernel::PluginEventDependencyHandle, operation: String, _event: serde_json::Value, _context: InvocationContext) -> futures::future::LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
