// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "example.settings-store@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:5cadeb256216c4260b1f2bf7ad2dad088d7fd3bf8d129690b17464e9a9cf0ec5";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const SETTINGS_STORE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SETTINGS_STORE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const SETTINGS_STORE_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const SETTINGS_STORE_CONTRACT: CapabilityReference<SettingsStoreClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_settings_store { () => { "{\"capability_id\":\"example.settings-store@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"change\",\"read\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_settings_store_client {
    () => { "{\"capability_id\":\"example.settings-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.settings-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_settings_store_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.settings-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_settings_store_client {
    () => { "{\"capability_id\":\"example.settings-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.settings-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const CHANGE_OPERATION: &str = "change";
pub const READ_OPERATION: &str = "read";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ChangeRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: i64,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "principal")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub principal: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ChangeResponse {
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ChangeError {
    Conflict,
    IdempotencyConflict,
    Invalid,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRequest {
    #[serde(rename = "principal")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub principal: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponse {
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadError {
    Conflict,
    IdempotencyConflict,
    Invalid,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct SettingsStoreChange;
impl RequestCapability for SettingsStoreChange {
    type Request = ChangeRequest;
    type Response = ChangeResponse;
    type DomainError = ChangeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CHANGE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SettingsStoreRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).change(context, request)
    }
}

#[derive(Debug)]
pub struct SettingsStoreRead;
impl RequestCapability for SettingsStoreRead {
    type Request = ReadRequest;
    type Response = ReadResponse;
    type DomainError = ReadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SettingsStoreRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read(context, request)
    }
}

impl serde::Serialize for ChangeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::Invalid => serializer.serialize_str("invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ChangeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid" => Ok(Self::Invalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::Invalid => serializer.serialize_str("invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid" => Ok(Self::Invalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_change_request(value: &ChangeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_change_request(wire: &str) -> Result<ChangeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_change_response(value: &ChangeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_change_response(wire: &str) -> Result<ChangeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_change_error(value: &ChangeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_change_error(wire: &str) -> Result<ChangeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_request(value: &ReadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_request(wire: &str) -> Result<ReadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_response(value: &ReadResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_response(wire: &str) -> Result<ReadResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_error(value: &ReadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_error(wire: &str) -> Result<ReadError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoSettingsStoreChangeResult {
    fn __lenso_into_result(self) -> Result<Result<ChangeResponse, ChangeError>, RuntimeFailure>;
}
impl __LensoIntoSettingsStoreChangeResult for Result<ChangeResponse, ChangeError> {
    fn __lenso_into_result(self) -> Result<Result<ChangeResponse, ChangeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSettingsStoreChangeResult for Result<Result<ChangeResponse, ChangeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ChangeResponse, ChangeError>, RuntimeFailure> { self }
}
impl __LensoIntoSettingsStoreChangeResult for Result<ChangeResponse, lenso_plugin_authoring::PluginError<ChangeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ChangeResponse, ChangeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSettingsStoreChangeResult for Result<ChangeResponse, SettingsStoreChangeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ChangeResponse, ChangeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SettingsStoreChangeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SettingsStoreChangeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoSettingsStoreReadResult {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure>;
}
impl __LensoIntoSettingsStoreReadResult for Result<ReadResponse, ReadError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSettingsStoreReadResult for Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { self }
}
impl __LensoIntoSettingsStoreReadResult for Result<ReadResponse, lenso_plugin_authoring::PluginError<ReadError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSettingsStoreReadResult for Result<ReadResponse, SettingsStoreReadInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SettingsStoreReadInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SettingsStoreReadInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait SettingsStoreProvider: fmt::Debug + 'static {
    fn change(&self, context: InvocationContext, request: ChangeRequest) -> NativeRequestFuture<SettingsStoreChange>;
    fn read(&self, context: InvocationContext, request: ReadRequest) -> NativeRequestFuture<SettingsStoreRead>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_settings_store {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSettingsStore;
        impl $crate::SettingsStoreProvider for $plugin {
        fn change(&self, context: __LensoNativeSupportSettingsStore::InvocationContext, request: $crate::ChangeRequest) -> __LensoNativeSupportSettingsStore::NativeRequestFuture<$crate::SettingsStoreChange> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::change(&plugin, context, request).await;
                $crate::__LensoIntoSettingsStoreChangeResult::__lenso_into_result(result)
            })
        }
        fn read(&self, context: __LensoNativeSupportSettingsStore::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportSettingsStore::NativeRequestFuture<$crate::SettingsStoreRead> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read(&plugin, context, request).await;
                $crate::__LensoIntoSettingsStoreReadResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_settings_store {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSettingsStore;
        impl $crate::SettingsStoreProvider for $object {
        fn change(&self, context: __LensoNativeSupportSettingsStore::InvocationContext, request: $crate::ChangeRequest) -> __LensoNativeSupportSettingsStore::NativeRequestFuture<$crate::SettingsStoreChange> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::change(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoSettingsStoreChangeResult::__lenso_into_result(result)
            })
        }
        fn read(&self, context: __LensoNativeSupportSettingsStore::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportSettingsStore::NativeRequestFuture<$crate::SettingsStoreRead> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoSettingsStoreReadResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_settings_store {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSettingsStore;
        impl $crate::SettingsStoreProvider for $object {
        fn change(&self, context: __LensoNativeSupportSettingsStore::InvocationContext, request: $crate::ChangeRequest) -> __LensoNativeSupportSettingsStore::NativeRequestFuture<$crate::SettingsStoreChange> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::SettingsStoreProvider>::change(plugin.as_ref(), context, request).await
            })
        }
        fn read(&self, context: __LensoNativeSupportSettingsStore::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportSettingsStore::NativeRequestFuture<$crate::SettingsStoreRead> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::SettingsStoreProvider>::read(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct SettingsStoreRequestEndpoint { provider: Rc<dyn SettingsStoreProvider> }

#[derive(Debug)]
pub struct SettingsStoreEndpoint<P: SettingsStoreProvider> { provider: Rc<P>, request_endpoint: SettingsStoreRequestEndpoint }
impl<P: SettingsStoreProvider> SettingsStoreEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SettingsStoreProvider> = provider.clone();
        Self { provider, request_endpoint: SettingsStoreRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SettingsStoreProvider> NativeRequestEndpoint for SettingsStoreEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CHANGE_OPERATION,
        READ_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CHANGE_OPERATION => {
                let Ok(request) = request.downcast::<ChangeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).change(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_OPERATION => {
                let Ok(request) = request.downcast::<ReadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_settings_store {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::SettingsStoreEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_settings_store {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_settings_store!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct SettingsStoreClient {
    change: NativeRequestHandle<SettingsStoreChange>,
    read: NativeRequestHandle<SettingsStoreRead>,
}
impl SettingsStoreClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn change(&self, request: ChangeRequest) -> Result<ChangeResponse, SettingsStoreChangeInvocationError> {
        self.change.invoke(CHANGE_OPERATION, request).await
            .map_err(SettingsStoreChangeInvocationError::Runtime)?
            .map_err(SettingsStoreChangeInvocationError::Domain)
    }

    pub async fn change_with_context(&self, context: InvocationContext, request: ChangeRequest) -> Result<ChangeResponse, SettingsStoreChangeInvocationError> {
        self.change.invoke_with_context(CHANGE_OPERATION, context, request).await
            .map_err(SettingsStoreChangeInvocationError::Runtime)?
            .map_err(SettingsStoreChangeInvocationError::Domain)
    }

    pub async fn read(&self, request: ReadRequest) -> Result<ReadResponse, SettingsStoreReadInvocationError> {
        self.read.invoke(READ_OPERATION, request).await
            .map_err(SettingsStoreReadInvocationError::Runtime)?
            .map_err(SettingsStoreReadInvocationError::Domain)
    }

    pub async fn read_with_context(&self, context: InvocationContext, request: ReadRequest) -> Result<ReadResponse, SettingsStoreReadInvocationError> {
        self.read.invoke_with_context(READ_OPERATION, context, request).await
            .map_err(SettingsStoreReadInvocationError::Runtime)?
            .map_err(SettingsStoreReadInvocationError::Domain)
    }
}

impl CapabilityClient for SettingsStoreClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            change: dependencies.one::<SettingsStoreChange>()?,
            read: dependencies.one::<SettingsStoreRead>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for SettingsStoreClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    change: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SettingsStoreChange>()?,
                    read: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SettingsStoreRead>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SettingsStoreChangeInvocationError {
    Domain(ChangeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SettingsStoreReadInvocationError {
    Domain(ReadError),
    Runtime(RuntimeFailure),
}
