// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "example.game-session@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const GAME_SESSION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const GAME_SESSION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_game_session { () => { "{\"capability_id\":\"example.game-session@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"play\"],\"operation_kinds\":{\"play\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_game_session_client { () => { "{\"capability_id\":\"example.game-session@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_game_session_client { () => { "{\"capability_id\":\"example.game-session@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const PLAY_OPERATION: &str = "play";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PlayRequest {
    #[serde(rename = "room")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub room: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PlayResponse {
    #[serde(rename = "action")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PlayError {
    ActorRequired,
    InvalidAction,
    NotAllowed,
    RoomClosed,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct GameSession;
pub type GameSessionEvent = StreamEvent<PlayResponse, PlayError>;
impl StreamCapability for GameSession {
    type OpenRequest = PlayRequest;
    type Message = PlayResponse;
    type DomainError = PlayError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for PlayError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ActorRequired => serializer.serialize_str("actor_required"),
            Self::InvalidAction => serializer.serialize_str("invalid_action"),
            Self::NotAllowed => serializer.serialize_str("not_allowed"),
            Self::RoomClosed => serializer.serialize_str("room_closed"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PlayError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "actor_required" => Ok(Self::ActorRequired),
                "invalid_action" => Ok(Self::InvalidAction),
                "not_allowed" => Ok(Self::NotAllowed),
                "room_closed" => Ok(Self::RoomClosed),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_play_request(value: &PlayRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_play_request(wire: &str) -> Result<PlayRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_play_response(value: &PlayResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_play_response(wire: &str) -> Result<PlayResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_play_error(value: &PlayError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_play_error(wire: &str) -> Result<PlayError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoGameSessionPlayStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, GameSessionInvocationError>;
}
impl<S> __LensoIntoGameSessionPlayStreamResult for Result<S, PlayError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, GameSessionInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(GameSessionInvocationError::Domain)
    }
}
impl<S> __LensoIntoGameSessionPlayStreamResult for Result<S, lenso_plugin_authoring::PluginError<PlayError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, GameSessionInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(GameSessionInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(GameSessionInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoGameSessionPlayStreamResult for Result<S, GameSessionInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, GameSessionInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

pub trait GameSessionProvider: fmt::Debug + 'static {
    fn play(&self, context: InvocationContext, request: PlayRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, GameSessionInvocationError>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_game_session {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportGameSession;
        impl $crate::GameSessionProvider for $plugin {
        fn play(&self, context: __LensoNativeSupportGameSession::InvocationContext, request: $crate::PlayRequest) -> __LensoNativeSupportGameSession::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportGameSession::NativeStreamSession>, $crate::GameSessionInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::play(&plugin, context, request).await;
                $crate::__LensoIntoGameSessionPlayStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
pub struct GameSessionEndpoint<P: GameSessionProvider> { provider: Rc<P> }
impl<P: GameSessionProvider> GameSessionEndpoint<P> {
    pub fn new(provider: P) -> Self { Self { provider: Rc::new(provider) } }
}

impl<P: GameSessionProvider> NativeStreamEndpoint for GameSessionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        PLAY_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            PLAY_OPERATION => {
                let Ok(request) = request.downcast::<PlayRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.play(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(GameSessionInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(GameSessionInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_game_session {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::GameSessionEndpoint::new($provider));
        (
            vec![],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_game_session {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_game_session!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct GameSessionClient {
    play: NativeStreamHandle<GameSession>,
}
impl GameSessionClient {
    pub fn new(handle: NativeStreamHandle<GameSession>) -> Self {
        Self { play: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn play(&self, request: PlayRequest) -> Result<NativeStream<GameSession>, GameSessionInvocationError> {
        self.play.open(PLAY_OPERATION, request).await
            .map_err(GameSessionInvocationError::Runtime)?
            .map_err(GameSessionInvocationError::Domain)
    }

    pub async fn play_with_context(&self, context: InvocationContext, request: PlayRequest) -> Result<NativeStream<GameSession>, GameSessionInvocationError> {
        self.play.open_with_context(PLAY_OPERATION, context, request).await
            .map_err(GameSessionInvocationError::Runtime)?
            .map_err(GameSessionInvocationError::Domain)
    }
}

impl CapabilityClient for GameSessionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            play: dependencies.one_stream::<GameSession>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for GameSessionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    play: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<GameSession>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum GameSessionInvocationError {
    Domain(PlayError),
    Runtime(RuntimeFailure),
}
