// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "example.agent.memory@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const MEMORY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const MEMORY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_memory { () => { "{\"capability_id\":\"example.agent.memory@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"append\",\"read\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_memory_client { () => { "{\"capability_id\":\"example.agent.memory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_memory_client { () => { "{\"capability_id\":\"example.agent.memory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const APPEND_OPERATION: &str = "append";
pub const READ_OPERATION: &str = "read";

pub use lenso_contract_runtime::{Uint64, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendRequest {
    #[serde(rename = "entry")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub entry: String,
    #[serde(rename = "key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub key: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendResponse {
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AppendError {
    InvalidKey,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRequest {
    #[serde(rename = "key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub key: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponse {
    #[serde(rename = "entries")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub entries: Vec<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadError {
    InvalidKey,
    MissingKey,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct MemoryAppend;
impl RequestCapability for MemoryAppend {
    type Request = AppendRequest;
    type Response = AppendResponse;
    type DomainError = AppendError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != APPEND_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<MemoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).append(context, request)
    }
}

#[derive(Debug)]
pub struct MemoryRead;
impl RequestCapability for MemoryRead {
    type Request = ReadRequest;
    type Response = ReadResponse;
    type DomainError = ReadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<MemoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read(context, request)
    }
}

impl serde::Serialize for AppendError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidKey => serializer.serialize_str("invalid_key"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AppendError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_key" => Ok(Self::InvalidKey),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidKey => serializer.serialize_str("invalid_key"),
            Self::MissingKey => serializer.serialize_str("missing_key"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_key" => Ok(Self::InvalidKey),
                "missing_key" => Ok(Self::MissingKey),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_append_request(value: &AppendRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_request(wire: &str) -> Result<AppendRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_append_response(value: &AppendResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_response(wire: &str) -> Result<AppendResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_append_error(value: &AppendError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_error(wire: &str) -> Result<AppendError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_request(value: &ReadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_request(wire: &str) -> Result<ReadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_response(value: &ReadResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_response(wire: &str) -> Result<ReadResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_error(value: &ReadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_error(wire: &str) -> Result<ReadError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoMemoryAppendResult {
    fn __lenso_into_result(self) -> Result<Result<AppendResponse, AppendError>, RuntimeFailure>;
}
impl __LensoIntoMemoryAppendResult for Result<AppendResponse, AppendError> {
    fn __lenso_into_result(self) -> Result<Result<AppendResponse, AppendError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoMemoryAppendResult for Result<Result<AppendResponse, AppendError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AppendResponse, AppendError>, RuntimeFailure> { self }
}
impl __LensoIntoMemoryAppendResult for Result<AppendResponse, lenso_plugin_authoring::PluginError<AppendError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AppendResponse, AppendError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoMemoryAppendResult for Result<AppendResponse, MemoryAppendInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AppendResponse, AppendError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(MemoryAppendInvocationError::Domain(error)) => Ok(Err(error)),
            Err(MemoryAppendInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoMemoryReadResult {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure>;
}
impl __LensoIntoMemoryReadResult for Result<ReadResponse, ReadError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoMemoryReadResult for Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { self }
}
impl __LensoIntoMemoryReadResult for Result<ReadResponse, lenso_plugin_authoring::PluginError<ReadError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoMemoryReadResult for Result<ReadResponse, MemoryReadInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(MemoryReadInvocationError::Domain(error)) => Ok(Err(error)),
            Err(MemoryReadInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait MemoryProvider: fmt::Debug + 'static {
    fn append(&self, context: InvocationContext, request: AppendRequest) -> NativeRequestFuture<MemoryAppend>;
    fn read(&self, context: InvocationContext, request: ReadRequest) -> NativeRequestFuture<MemoryRead>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_memory {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportMemory;
        impl $crate::MemoryProvider for $plugin {
        fn append(&self, context: __LensoNativeSupportMemory::InvocationContext, request: $crate::AppendRequest) -> __LensoNativeSupportMemory::NativeRequestFuture<$crate::MemoryAppend> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::append(&plugin, context, request).await;
                $crate::__LensoIntoMemoryAppendResult::__lenso_into_result(result)
            })
        }
        fn read(&self, context: __LensoNativeSupportMemory::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportMemory::NativeRequestFuture<$crate::MemoryRead> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read(&plugin, context, request).await;
                $crate::__LensoIntoMemoryReadResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct MemoryRequestEndpoint { provider: Rc<dyn MemoryProvider> }

#[derive(Debug)]
pub struct MemoryEndpoint<P: MemoryProvider> { provider: Rc<P>, request_endpoint: MemoryRequestEndpoint }
impl<P: MemoryProvider> MemoryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn MemoryProvider> = provider.clone();
        Self { provider, request_endpoint: MemoryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: MemoryProvider> NativeRequestEndpoint for MemoryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        APPEND_OPERATION,
        READ_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            APPEND_OPERATION => {
                let Ok(request) = request.downcast::<AppendRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).append(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_OPERATION => {
                let Ok(request) = request.downcast::<ReadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_memory {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::MemoryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_memory {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_memory!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct MemoryClient {
    append: NativeRequestHandle<MemoryAppend>,
    read: NativeRequestHandle<MemoryRead>,
}
impl MemoryClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn append(&self, request: AppendRequest) -> Result<AppendResponse, MemoryAppendInvocationError> {
        self.append.invoke(APPEND_OPERATION, request).await
            .map_err(MemoryAppendInvocationError::Runtime)?
            .map_err(MemoryAppendInvocationError::Domain)
    }

    pub async fn append_with_context(&self, context: InvocationContext, request: AppendRequest) -> Result<AppendResponse, MemoryAppendInvocationError> {
        self.append.invoke_with_context(APPEND_OPERATION, context, request).await
            .map_err(MemoryAppendInvocationError::Runtime)?
            .map_err(MemoryAppendInvocationError::Domain)
    }

    pub async fn read(&self, request: ReadRequest) -> Result<ReadResponse, MemoryReadInvocationError> {
        self.read.invoke(READ_OPERATION, request).await
            .map_err(MemoryReadInvocationError::Runtime)?
            .map_err(MemoryReadInvocationError::Domain)
    }

    pub async fn read_with_context(&self, context: InvocationContext, request: ReadRequest) -> Result<ReadResponse, MemoryReadInvocationError> {
        self.read.invoke_with_context(READ_OPERATION, context, request).await
            .map_err(MemoryReadInvocationError::Runtime)?
            .map_err(MemoryReadInvocationError::Domain)
    }
}

impl CapabilityClient for MemoryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            append: dependencies.one::<MemoryAppend>()?,
            read: dependencies.one::<MemoryRead>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for MemoryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    append: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<MemoryAppend>()?,
                    read: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<MemoryRead>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum MemoryAppendInvocationError {
    Domain(AppendError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum MemoryReadInvocationError {
    Domain(ReadError),
    Runtime(RuntimeFailure),
}
