// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, RuntimeFailure, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, StreamCapability, StreamEvent};

pub const CAPABILITY_ID: &str = "example.agent.model@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const MODEL_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const MODEL_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const COMPLETE_OPERATION: &str = "complete";

pub type Int64 = String;
pub type Uint64 = String;
pub type Bytes = String;
pub type Timestamp = String;
pub type Duration = String;
pub type OptionalValue<T> = Option<Option<T>>;

#[allow(dead_code)]
fn deserialize_required<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    <T as serde::Deserialize>::deserialize(deserializer)
}

#[allow(dead_code, clippy::option_option)]
fn deserialize_optional_value<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    Ok(Some(<Option<T> as serde::Deserialize>::deserialize(deserializer)?))
}

#[allow(dead_code)]
fn validate_portable_json_value(value: &serde_json::Value) -> Result<(), String> {
    match value {
        serde_json::Value::Number(number) => {
            let safe = number.as_i64().is_some_and(|value| (-9_007_199_254_740_991..=9_007_199_254_740_991).contains(&value))
                || number.as_u64().is_some_and(|value| value <= 9_007_199_254_740_991)
                || (number.is_f64() && number.as_f64().is_some_and(|value| value.is_finite() && (value.abs() <= 9_007_199_254_740_991.0 || value.fract() != 0.0)));
            if !safe {
                return Err("wire JSON contains an unsafe number".to_owned());
            }
        }
        serde_json::Value::Array(values) => {
            for value in values {
                validate_portable_json_value(value)?;
            }
        }
        serde_json::Value::Object(values) => {
            for value in values.values() {
                validate_portable_json_value(value)?;
            }
        }
        serde_json::Value::Null | serde_json::Value::Bool(_) | serde_json::Value::String(_) => {}
    }
    Ok(())
}

#[allow(dead_code)]
fn portable_json_error(detail: String) -> serde_json::Error {
    serde_json::Error::io(std::io::Error::new(std::io::ErrorKind::InvalidData, detail))
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UnknownDomainError {
    pub code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
    #[serde(default, flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteRequest {
    #[serde(rename = "memory")]
    #[serde(deserialize_with = "deserialize_required")]
    pub memory: Vec<String>,
    #[serde(rename = "prompt")]
    #[serde(deserialize_with = "deserialize_required")]
    pub prompt: String,
    #[serde(rename = "tool_output")]
    #[serde(deserialize_with = "deserialize_required")]
    pub tool_output: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteResponse {
    #[serde(rename = "delta")]
    #[serde(deserialize_with = "deserialize_required")]
    pub delta: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompleteError {
    ContextTooLarge,
    InvalidPrompt,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Model;
pub type ModelEvent = StreamEvent<CompleteResponse, CompleteError>;
impl StreamCapability for Model {
    type OpenRequest = CompleteRequest;
    type Message = CompleteResponse;
    type DomainError = CompleteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for CompleteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContextTooLarge => serializer.serialize_str("context_too_large"),
            Self::InvalidPrompt => serializer.serialize_str("invalid_prompt"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CompleteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "context_too_large" => Ok(Self::ContextTooLarge),
                "invalid_prompt" => Ok(Self::InvalidPrompt),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_complete_request(value: &CompleteRequest) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_complete_request(wire: &str) -> Result<CompleteRequest, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_complete_response(value: &CompleteResponse) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_complete_response(wire: &str) -> Result<CompleteResponse, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_complete_error(value: &CompleteError) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_complete_error(wire: &str) -> Result<CompleteError, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }

pub trait ModelProvider: fmt::Debug + 'static {
    fn complete(&self, context: InvocationContext, request: CompleteRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, ModelInvocationError>>;
}

#[derive(Debug)]
pub struct ModelEndpoint<P> { provider: Rc<P> }
impl<P: ModelProvider> ModelEndpoint<P> {
    pub fn new(provider: P) -> Self { Self { provider: Rc::new(provider) } }
}

impl<P: ModelProvider> NativeStreamEndpoint for ModelEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        COMPLETE_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            COMPLETE_OPERATION => {
                let Ok(request) = request.downcast::<CompleteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.complete(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(ModelInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ModelInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct ModelClient {
    complete: NativeStreamHandle<Model>,
}
impl ModelClient {
    pub fn new(handle: NativeStreamHandle<Model>) -> Self {
        Self { complete: handle }
    }

    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            complete: dependencies.one_stream::<Model>()?,
        })
    }

    pub async fn complete(&self, request: CompleteRequest) -> Result<NativeStream<Model>, ModelInvocationError> {
        self.complete.open(COMPLETE_OPERATION, request).await
            .map_err(ModelInvocationError::Runtime)?
            .map_err(ModelInvocationError::Domain)
    }

    pub async fn complete_with_context(&self, context: InvocationContext, request: CompleteRequest) -> Result<NativeStream<Model>, ModelInvocationError> {
        self.complete.open_with_context(COMPLETE_OPERATION, context, request).await
            .map_err(ModelInvocationError::Runtime)?
            .map_err(ModelInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ModelInvocationError {
    Domain(CompleteError),
    Runtime(RuntimeFailure),
}
