// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{EventCapability, EventPublishResult, InvocationContext, NativeEventEndpoint, NativeEventHandle, PluginDependencies, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "example.agent.progress@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const PROGRESS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PROGRESS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_progress { () => { "{\"capability_id\":\"example.agent.progress@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"update\"],\"operation_kinds\":{\"update\":\"event\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_progress_client { () => { "{\"capability_id\":\"example.agent.progress@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_progress_client { () => { "{\"capability_id\":\"example.agent.progress@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const UPDATE_OPERATION: &str = "update";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpdateRequest {
    #[serde(rename = "detail")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub detail: String,
    #[serde(rename = "run_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub run_id: String,
    #[serde(rename = "stage")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub stage: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UpdateError {
    SubscriberFailed,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Progress;
impl EventCapability for Progress {
    type Event = UpdateRequest;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for UpdateError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::SubscriberFailed => serializer.serialize_str("subscriber_failed"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for UpdateError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "subscriber_failed" => Ok(Self::SubscriberFailed),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_update_request(value: &UpdateRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_request(wire: &str) -> Result<UpdateRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_update_response(value: &()) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_response(wire: &str) -> Result<(), serde_json::Error> { decode_portable_json(wire) }
pub fn encode_update_error(value: &UpdateError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_error(wire: &str) -> Result<UpdateError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_update_event(value: &UpdateRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_event(wire: &str) -> Result<UpdateRequest, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoProgressUpdateEventResult {
    fn __lenso_into_result(self) -> Result<(), RuntimeFailure>;
}
impl __LensoIntoProgressUpdateEventResult for () {
    fn __lenso_into_result(self) -> Result<(), RuntimeFailure> { Ok(()) }
}
impl __LensoIntoProgressUpdateEventResult for Result<(), RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<(), RuntimeFailure> { self }
}

pub trait ProgressProvider: fmt::Debug + 'static {
    fn update(&self, context: InvocationContext, event: UpdateRequest) -> LocalBoxFuture<'static, Result<(), RuntimeFailure>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_progress {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportProgress;
        impl $crate::ProgressProvider for $plugin {
        fn update(&self, context: __LensoNativeSupportProgress::InvocationContext, event: $crate::UpdateRequest) -> __LensoNativeSupportProgress::LocalBoxFuture<'static, Result<(), __LensoNativeSupportProgress::RuntimeFailure>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::update(&plugin, context, event).await;
                $crate::__LensoIntoProgressUpdateEventResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
pub struct ProgressEndpoint<P: ProgressProvider> { provider: Rc<P> }
impl<P: ProgressProvider> ProgressEndpoint<P> {
    pub fn new(provider: P) -> Self { Self { provider: Rc::new(provider) } }
}

impl<P: ProgressProvider> NativeEventEndpoint for ProgressEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        UPDATE_OPERATION,
    ] }
    fn publish(&self, operation: &str, event: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        match operation {
            UPDATE_OPERATION => {
                let Ok(event) = event.downcast::<UpdateRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                Rc::clone(&self.provider).update(context, *event)
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_progress {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ProgressEndpoint::new($provider));
        (
            vec![],
            vec![],
            vec![endpoint as ::std::rc::Rc<dyn __LensoNativeSupport::NativeEventEndpoint>],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_progress {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_progress!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ProgressClient {
    update: NativeEventHandle<Progress>,
}
impl ProgressClient {
    pub fn new(handle: NativeEventHandle<Progress>) -> Self {
        Self { update: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn update(&self, event: UpdateRequest) -> Vec<EventPublishResult> {
        self.update.publish(UPDATE_OPERATION, event).await
    }

    pub async fn update_with_context(&self, context: InvocationContext, event: UpdateRequest) -> Vec<EventPublishResult> {
        self.update.publish_with_context(UPDATE_OPERATION, context, event).await
    }
}

impl CapabilityClient for ProgressClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            update: dependencies.many_event::<Progress>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ProgressClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    update: binding.event_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Progress>()?,
                    },
                ))
            })
            .collect()
    }
}
