// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "example.greeting@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const GREETING_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const GREETING_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_greeting { () => { "{\"capability_id\":\"example.greeting@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"greet\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_greeting_client { () => { "{\"capability_id\":\"example.greeting@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_greeting_client { () => { "{\"capability_id\":\"example.greeting@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const GREET_OPERATION: &str = "greet";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GreetRequest {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GreetResponse {
    #[serde(rename = "message")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GreetError {
    EmptyName,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Greeting;
impl RequestCapability for Greeting {
    type Request = GreetRequest;
    type Response = GreetResponse;
    type DomainError = GreetError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GREET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<GreetingRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).greet(context, request)
    }
}

impl serde::Serialize for GreetError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::EmptyName => serializer.serialize_str("empty_name"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GreetError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "empty_name" => Ok(Self::EmptyName),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_greet_request(value: &GreetRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_greet_request(wire: &str) -> Result<GreetRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_greet_response(value: &GreetResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_greet_response(wire: &str) -> Result<GreetResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_greet_error(value: &GreetError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_greet_error(wire: &str) -> Result<GreetError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoGreetingGreetResult {
    fn __lenso_into_result(self) -> Result<Result<GreetResponse, GreetError>, RuntimeFailure>;
}
impl __LensoIntoGreetingGreetResult for Result<GreetResponse, GreetError> {
    fn __lenso_into_result(self) -> Result<Result<GreetResponse, GreetError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoGreetingGreetResult for Result<Result<GreetResponse, GreetError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GreetResponse, GreetError>, RuntimeFailure> { self }
}
impl __LensoIntoGreetingGreetResult for Result<GreetResponse, lenso_plugin_authoring::PluginError<GreetError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GreetResponse, GreetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoGreetingGreetResult for Result<GreetResponse, GreetingInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GreetResponse, GreetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(GreetingInvocationError::Domain(error)) => Ok(Err(error)),
            Err(GreetingInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait GreetingProvider: fmt::Debug + 'static {
    fn greet(&self, context: InvocationContext, request: GreetRequest) -> NativeRequestFuture<Greeting>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_greeting {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportGreeting;
        impl $crate::GreetingProvider for $plugin {
        fn greet(&self, context: __LensoNativeSupportGreeting::InvocationContext, request: $crate::GreetRequest) -> __LensoNativeSupportGreeting::NativeRequestFuture<$crate::Greeting> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::greet(&plugin, context, request).await;
                $crate::__LensoIntoGreetingGreetResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct GreetingRequestEndpoint { provider: Rc<dyn GreetingProvider> }

#[derive(Debug)]
pub struct GreetingEndpoint<P: GreetingProvider> { provider: Rc<P>, request_endpoint: GreetingRequestEndpoint }
impl<P: GreetingProvider> GreetingEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn GreetingProvider> = provider.clone();
        Self { provider, request_endpoint: GreetingRequestEndpoint { provider: request_provider } }
    }
}

impl<P: GreetingProvider> NativeRequestEndpoint for GreetingEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GREET_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GREET_OPERATION => {
                let Ok(request) = request.downcast::<GreetRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).greet(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_greeting {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::GreetingEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_greeting {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_greeting!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct GreetingClient {
    greet: NativeRequestHandle<Greeting>,
}
impl GreetingClient {
    pub fn new(handle: NativeRequestHandle<Greeting>) -> Self {
        Self { greet: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn greet(&self, request: GreetRequest) -> Result<GreetResponse, GreetingInvocationError> {
        self.greet.invoke(GREET_OPERATION, request).await
            .map_err(GreetingInvocationError::Runtime)?
            .map_err(GreetingInvocationError::Domain)
    }

    pub async fn greet_with_context(&self, context: InvocationContext, request: GreetRequest) -> Result<GreetResponse, GreetingInvocationError> {
        self.greet.invoke_with_context(GREET_OPERATION, context, request).await
            .map_err(GreetingInvocationError::Runtime)?
            .map_err(GreetingInvocationError::Domain)
    }
}

impl CapabilityClient for GreetingClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            greet: dependencies.one::<Greeting>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for GreetingClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    greet: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Greeting>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum GreetingInvocationError {
    Domain(GreetError),
    Runtime(RuntimeFailure),
}
