// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.story.query@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const QUERY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const QUERY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_query { () => { "{\"capability_id\":\"lenso.story.query@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"timeline\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_query_client { () => { "{\"capability_id\":\"lenso.story.query@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_query_client { () => { "{\"capability_id\":\"lenso.story.query@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const TIMELINE_OPERATION: &str = "timeline";

pub use lenso_contract_runtime::{Timestamp, Uint64, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TimelineRequest {
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "subject_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TimelineResponse {
    #[serde(rename = "entries")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub entries: Vec<TimelineResponseEntriesItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TimelineResponseEntriesItem {
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_id: String,
    #[serde(rename = "event_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_type: String,
    #[serde(rename = "event_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_version: i64,
    #[serde(rename = "facts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub facts: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
    #[serde(rename = "source_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_instance: String,
    #[serde(rename = "subject_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TimelineError {
    InvalidQuery,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Query;
impl RequestCapability for Query {
    type Request = TimelineRequest;
    type Response = TimelineResponse;
    type DomainError = TimelineError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != TIMELINE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<QueryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).timeline(context, request)
    }
}

impl serde::Serialize for TimelineError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for TimelineError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_query" => Ok(Self::InvalidQuery),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_timeline_request(value: &TimelineRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_timeline_request(wire: &str) -> Result<TimelineRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_timeline_response(value: &TimelineResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_timeline_response(wire: &str) -> Result<TimelineResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_timeline_error(value: &TimelineError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_timeline_error(wire: &str) -> Result<TimelineError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoQueryTimelineResult {
    fn __lenso_into_result(self) -> Result<Result<TimelineResponse, TimelineError>, RuntimeFailure>;
}
impl __LensoIntoQueryTimelineResult for Result<TimelineResponse, TimelineError> {
    fn __lenso_into_result(self) -> Result<Result<TimelineResponse, TimelineError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoQueryTimelineResult for Result<Result<TimelineResponse, TimelineError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<TimelineResponse, TimelineError>, RuntimeFailure> { self }
}
impl __LensoIntoQueryTimelineResult for Result<TimelineResponse, lenso_plugin_authoring::PluginError<TimelineError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<TimelineResponse, TimelineError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoQueryTimelineResult for Result<TimelineResponse, QueryInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<TimelineResponse, TimelineError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(QueryInvocationError::Domain(error)) => Ok(Err(error)),
            Err(QueryInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait QueryProvider: fmt::Debug + 'static {
    fn timeline(&self, context: InvocationContext, request: TimelineRequest) -> NativeRequestFuture<Query>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_query {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportQuery;
        impl $crate::QueryProvider for $plugin {
        fn timeline(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::TimelineRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::Query> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::timeline(&plugin, context, request).await;
                $crate::__LensoIntoQueryTimelineResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct QueryRequestEndpoint { provider: Rc<dyn QueryProvider> }

#[derive(Debug)]
pub struct QueryEndpoint<P: QueryProvider> { provider: Rc<P>, request_endpoint: QueryRequestEndpoint }
impl<P: QueryProvider> QueryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn QueryProvider> = provider.clone();
        Self { provider, request_endpoint: QueryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: QueryProvider> NativeRequestEndpoint for QueryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        TIMELINE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            TIMELINE_OPERATION => {
                let Ok(request) = request.downcast::<TimelineRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).timeline(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_query {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::QueryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_query {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_query!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct QueryClient {
    timeline: NativeRequestHandle<Query>,
}
impl QueryClient {
    pub fn new(handle: NativeRequestHandle<Query>) -> Self {
        Self { timeline: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn timeline(&self, request: TimelineRequest) -> Result<TimelineResponse, QueryInvocationError> {
        self.timeline.invoke(TIMELINE_OPERATION, request).await
            .map_err(QueryInvocationError::Runtime)?
            .map_err(QueryInvocationError::Domain)
    }

    pub async fn timeline_with_context(&self, context: InvocationContext, request: TimelineRequest) -> Result<TimelineResponse, QueryInvocationError> {
        self.timeline.invoke_with_context(TIMELINE_OPERATION, context, request).await
            .map_err(QueryInvocationError::Runtime)?
            .map_err(QueryInvocationError::Domain)
    }
}

impl CapabilityClient for QueryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            timeline: dependencies.one::<Query>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for QueryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    timeline: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Query>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum QueryInvocationError {
    Domain(TimelineError),
    Runtime(RuntimeFailure),
}
