// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "example.document-sync@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:b0213b03351b76a29a2298c7f6338dd999acdefc1d1e6b50e8b67cbb63c08422";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const DOCUMENT_SYNC_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const DOCUMENT_SYNC_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const DOCUMENT_SYNC_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const DOCUMENT_SYNC_CONTRACT: CapabilityReference<DocumentSyncClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_document_sync { () => { "{\"capability_id\":\"example.document-sync@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"sync\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_document_sync_client {
    () => { "{\"capability_id\":\"example.document-sync@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.document-sync@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_document_sync_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.document-sync@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_document_sync_client {
    () => { "{\"capability_id\":\"example.document-sync@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"example.document-sync@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const SYNC_OPERATION: &str = "sync";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SyncRequest {
    #[serde(rename = "document")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub document: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SyncResponse {
    #[serde(rename = "document")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub document: String,
    #[serde(rename = "text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SyncError {
    AlreadyRunning,
    NotFound,
    WriteFailed,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct DocumentSync;
impl RequestCapability for DocumentSync {
    type Request = SyncRequest;
    type Response = SyncResponse;
    type DomainError = SyncError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SYNC_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DocumentSyncRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).sync(context, request)
    }
}

impl serde::Serialize for SyncError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyRunning => serializer.serialize_str("already_running"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::WriteFailed => serializer.serialize_str("write_failed"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SyncError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_running" => Ok(Self::AlreadyRunning),
                "not_found" => Ok(Self::NotFound),
                "write_failed" => Ok(Self::WriteFailed),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_sync_request(value: &SyncRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sync_request(wire: &str) -> Result<SyncRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_sync_response(value: &SyncResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sync_response(wire: &str) -> Result<SyncResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_sync_error(value: &SyncError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sync_error(wire: &str) -> Result<SyncError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoDocumentSyncSyncResult {
    fn __lenso_into_result(self) -> Result<Result<SyncResponse, SyncError>, RuntimeFailure>;
}
impl __LensoIntoDocumentSyncSyncResult for Result<SyncResponse, SyncError> {
    fn __lenso_into_result(self) -> Result<Result<SyncResponse, SyncError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDocumentSyncSyncResult for Result<Result<SyncResponse, SyncError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SyncResponse, SyncError>, RuntimeFailure> { self }
}
impl __LensoIntoDocumentSyncSyncResult for Result<SyncResponse, lenso_plugin_authoring::PluginError<SyncError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SyncResponse, SyncError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDocumentSyncSyncResult for Result<SyncResponse, DocumentSyncInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SyncResponse, SyncError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DocumentSyncInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DocumentSyncInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait DocumentSyncProvider: fmt::Debug + 'static {
    fn sync(&self, context: InvocationContext, request: SyncRequest) -> NativeRequestFuture<DocumentSync>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_document_sync {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDocumentSync;
        impl $crate::DocumentSyncProvider for $plugin {
        fn sync(&self, context: __LensoNativeSupportDocumentSync::InvocationContext, request: $crate::SyncRequest) -> __LensoNativeSupportDocumentSync::NativeRequestFuture<$crate::DocumentSync> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::sync(&plugin, context, request).await;
                $crate::__LensoIntoDocumentSyncSyncResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_document_sync {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDocumentSync;
        impl $crate::DocumentSyncProvider for $object {
        fn sync(&self, context: __LensoNativeSupportDocumentSync::InvocationContext, request: $crate::SyncRequest) -> __LensoNativeSupportDocumentSync::NativeRequestFuture<$crate::DocumentSync> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::sync(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoDocumentSyncSyncResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_document_sync {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDocumentSync;
        impl $crate::DocumentSyncProvider for $object {
        fn sync(&self, context: __LensoNativeSupportDocumentSync::InvocationContext, request: $crate::SyncRequest) -> __LensoNativeSupportDocumentSync::NativeRequestFuture<$crate::DocumentSync> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::DocumentSyncProvider>::sync(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct DocumentSyncRequestEndpoint { provider: Rc<dyn DocumentSyncProvider> }

#[derive(Debug)]
pub struct DocumentSyncEndpoint<P: DocumentSyncProvider> { provider: Rc<P>, request_endpoint: DocumentSyncRequestEndpoint }
impl<P: DocumentSyncProvider> DocumentSyncEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn DocumentSyncProvider> = provider.clone();
        Self { provider, request_endpoint: DocumentSyncRequestEndpoint { provider: request_provider } }
    }
}

impl<P: DocumentSyncProvider> NativeRequestEndpoint for DocumentSyncEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SYNC_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SYNC_OPERATION => {
                let Ok(request) = request.downcast::<SyncRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).sync(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_document_sync {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::DocumentSyncEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_document_sync {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_document_sync!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct DocumentSyncClient {
    sync: NativeRequestHandle<DocumentSync>,
}
impl DocumentSyncClient {
    pub fn new(handle: NativeRequestHandle<DocumentSync>) -> Self {
        Self { sync: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn sync(&self, request: SyncRequest) -> Result<SyncResponse, DocumentSyncInvocationError> {
        self.sync.invoke(SYNC_OPERATION, request).await
            .map_err(DocumentSyncInvocationError::Runtime)?
            .map_err(DocumentSyncInvocationError::Domain)
    }

    pub async fn sync_with_context(&self, context: InvocationContext, request: SyncRequest) -> Result<SyncResponse, DocumentSyncInvocationError> {
        self.sync.invoke_with_context(SYNC_OPERATION, context, request).await
            .map_err(DocumentSyncInvocationError::Runtime)?
            .map_err(DocumentSyncInvocationError::Domain)
    }
}

impl CapabilityClient for DocumentSyncClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            sync: dependencies.one::<DocumentSync>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for DocumentSyncClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    sync: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DocumentSync>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum DocumentSyncInvocationError {
    Domain(SyncError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct DocumentSyncGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> DocumentSyncGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[SYNC_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn sync(&self, request: &SyncRequest) -> Result<SyncResponse, lenso_guest_sdk::GuestError<SyncError>> {
        self.capability.request(SYNC_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct DocumentSyncJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for DocumentSyncJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[SYNC_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            SYNC_OPERATION => {
                let value = request.downcast_ref::<SyncRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SYNC_OPERATION => serde_json::from_value::<SyncResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SYNC_OPERATION => serde_json::from_value::<SyncError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            SYNC_OPERATION => {
                let request = serde_json::from_value::<SyncRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<DocumentSync>()?;
                    match handle.invoke_with_context(SYNC_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
