// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "example.counter@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = false;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const COUNTER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const COUNTER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_counter { () => { "{\"capability_id\":\"example.counter@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"increment\",\"read\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_counter_client { () => { "{\"capability_id\":\"example.counter@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_counter_client { () => { "{\"capability_id\":\"example.counter@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const INCREMENT_OPERATION: &str = "increment";
pub const READ_OPERATION: &str = "read";

pub use lenso_contract_runtime::{Uint64, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IncrementRequest {
    #[serde(rename = "amount")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub amount: i64,
    #[serde(rename = "key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub key: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IncrementResponse {
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum IncrementError {
    InvalidKey,
    MissingKey,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRequest {
    #[serde(rename = "key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub key: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponse {
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadError {
    InvalidKey,
    MissingKey,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct CounterIncrement;
impl RequestCapability for CounterIncrement {
    type Request = IncrementRequest;
    type Response = IncrementResponse;
    type DomainError = IncrementError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INCREMENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CounterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).increment(context, request)
    }
}

#[derive(Debug)]
pub struct CounterRead;
impl RequestCapability for CounterRead {
    type Request = ReadRequest;
    type Response = ReadResponse;
    type DomainError = ReadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CounterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read(context, request)
    }
}

impl serde::Serialize for IncrementError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidKey => serializer.serialize_str("invalid_key"),
            Self::MissingKey => serializer.serialize_str("missing_key"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for IncrementError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_key" => Ok(Self::InvalidKey),
                "missing_key" => Ok(Self::MissingKey),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidKey => serializer.serialize_str("invalid_key"),
            Self::MissingKey => serializer.serialize_str("missing_key"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_key" => Ok(Self::InvalidKey),
                "missing_key" => Ok(Self::MissingKey),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_increment_request(value: &IncrementRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_increment_request(wire: &str) -> Result<IncrementRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_increment_response(value: &IncrementResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_increment_response(wire: &str) -> Result<IncrementResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_increment_error(value: &IncrementError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_increment_error(wire: &str) -> Result<IncrementError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_request(value: &ReadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_request(wire: &str) -> Result<ReadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_response(value: &ReadResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_response(wire: &str) -> Result<ReadResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_error(value: &ReadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_error(wire: &str) -> Result<ReadError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoCounterIncrementResult {
    fn __lenso_into_result(self) -> Result<Result<IncrementResponse, IncrementError>, RuntimeFailure>;
}
impl __LensoIntoCounterIncrementResult for Result<IncrementResponse, IncrementError> {
    fn __lenso_into_result(self) -> Result<Result<IncrementResponse, IncrementError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCounterIncrementResult for Result<Result<IncrementResponse, IncrementError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<IncrementResponse, IncrementError>, RuntimeFailure> { self }
}
impl __LensoIntoCounterIncrementResult for Result<IncrementResponse, lenso_plugin_authoring::PluginError<IncrementError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<IncrementResponse, IncrementError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCounterIncrementResult for Result<IncrementResponse, CounterIncrementInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<IncrementResponse, IncrementError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CounterIncrementInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CounterIncrementInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoCounterReadResult {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure>;
}
impl __LensoIntoCounterReadResult for Result<ReadResponse, ReadError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCounterReadResult for Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { self }
}
impl __LensoIntoCounterReadResult for Result<ReadResponse, lenso_plugin_authoring::PluginError<ReadError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCounterReadResult for Result<ReadResponse, CounterReadInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CounterReadInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CounterReadInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait CounterProvider: fmt::Debug + 'static {
    fn increment(&self, context: InvocationContext, request: IncrementRequest) -> NativeRequestFuture<CounterIncrement>;
    fn read(&self, context: InvocationContext, request: ReadRequest) -> NativeRequestFuture<CounterRead>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_counter {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportCounter;
        impl $crate::CounterProvider for $plugin {
        fn increment(&self, context: __LensoNativeSupportCounter::InvocationContext, request: $crate::IncrementRequest) -> __LensoNativeSupportCounter::NativeRequestFuture<$crate::CounterIncrement> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::increment(&plugin, context, request).await;
                $crate::__LensoIntoCounterIncrementResult::__lenso_into_result(result)
            })
        }
        fn read(&self, context: __LensoNativeSupportCounter::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportCounter::NativeRequestFuture<$crate::CounterRead> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read(&plugin, context, request).await;
                $crate::__LensoIntoCounterReadResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct CounterRequestEndpoint { provider: Rc<dyn CounterProvider> }

#[derive(Debug)]
pub struct CounterEndpoint<P: CounterProvider> { provider: Rc<P>, request_endpoint: CounterRequestEndpoint }
impl<P: CounterProvider> CounterEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn CounterProvider> = provider.clone();
        Self { provider, request_endpoint: CounterRequestEndpoint { provider: request_provider } }
    }
}

impl<P: CounterProvider> NativeRequestEndpoint for CounterEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        INCREMENT_OPERATION,
        READ_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            INCREMENT_OPERATION => {
                let Ok(request) = request.downcast::<IncrementRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).increment(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_OPERATION => {
                let Ok(request) = request.downcast::<ReadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_counter {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::CounterEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_counter {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_counter!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct CounterClient {
    increment: NativeRequestHandle<CounterIncrement>,
    read: NativeRequestHandle<CounterRead>,
}
impl CounterClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn increment(&self, request: IncrementRequest) -> Result<IncrementResponse, CounterIncrementInvocationError> {
        self.increment.invoke(INCREMENT_OPERATION, request).await
            .map_err(CounterIncrementInvocationError::Runtime)?
            .map_err(CounterIncrementInvocationError::Domain)
    }

    pub async fn increment_with_context(&self, context: InvocationContext, request: IncrementRequest) -> Result<IncrementResponse, CounterIncrementInvocationError> {
        self.increment.invoke_with_context(INCREMENT_OPERATION, context, request).await
            .map_err(CounterIncrementInvocationError::Runtime)?
            .map_err(CounterIncrementInvocationError::Domain)
    }

    pub async fn read(&self, request: ReadRequest) -> Result<ReadResponse, CounterReadInvocationError> {
        self.read.invoke(READ_OPERATION, request).await
            .map_err(CounterReadInvocationError::Runtime)?
            .map_err(CounterReadInvocationError::Domain)
    }

    pub async fn read_with_context(&self, context: InvocationContext, request: ReadRequest) -> Result<ReadResponse, CounterReadInvocationError> {
        self.read.invoke_with_context(READ_OPERATION, context, request).await
            .map_err(CounterReadInvocationError::Runtime)?
            .map_err(CounterReadInvocationError::Domain)
    }
}

impl CapabilityClient for CounterClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            increment: dependencies.one::<CounterIncrement>()?,
            read: dependencies.one::<CounterRead>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for CounterClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    increment: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<CounterIncrement>()?,
                    read: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<CounterRead>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CounterIncrementInvocationError {
    Domain(IncrementError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum CounterReadInvocationError {
    Domain(ReadError),
    Runtime(RuntimeFailure),
}
